更新一些局域网路由器的域名
v2fly/domain-list-community pull request #1077
Opened 2022-08-11 10:57 UTC by fengguowudi

但是有些局域网路由器的域名在广域网被别的网站已经使用
如 `p.to` `routerlogin.com`等 是否合并由大佬们决定啦

2022-08-11 12:04 UTC, rootmelo92118 commented
@IceCodeNew 這部分就交由你定奪了，我對`private`分類不是很熟悉

2022-08-11 12:23 UTC, IceCodeNew requested changes

2022-08-11 12:23 UTC, IceCodeNew commented on data/geolocation-cn
> +kuaiduizuoye.com
一个 PR 里做一件事，这个更改应该提别的 PR
// 何况这个域名已经在别的 PR 里加上了

2022-08-11 12:23 UTC, IceCodeNew commented on data/private
> +p.to
除非提供明确的资料证明这个域名会被特定路由器解析到 **内网地址**，否则这些域名都不会被通过

2022-08-11 12:23 UTC, IceCodeNew commented on data/private
> +full:setmeup.arubanetworks.com
需要补充资料

2022-08-11 14:28 UTC, merged

2022-08-11 14:46 UTC, IceCodeNew commented
what, the, fuck, have you done. 🤨

2022-08-11 15:04 UTC, fengguowudi commented
> what, the, fuck, have you done. 🤨

我干啥了？？？？？？？？？？？？？

2022-08-11 16:51 UTC, IceCodeNew commented
你把自己能确定是特定路由器当作内网域名在用的站点列一下吧，PR 我来提
你把这个 pr 的提交历史搞坏了

2022-08-12 02:26 UTC, rootmelo92118 commented
> 你把自己能确定是特定路由器当作内网域名在用的站点列一下吧，PR 我来提
> 你把这个 pr 的提交历史搞坏了
<img width="1440" alt="截圖 2022-08-12 上午10 24 45" src="https://user-images.githubusercontent.com/32770959/184273531-fa724e9e-a5a8-46d4-ad74-8a18d9e83636.png">
<img width="1440" alt="截圖 2022-08-11 下午9 15 33" src="https://user-images.githubusercontent.com/32770959/184273545-191cc81c-9c0b-4dfe-978e-ae8a91ed4768.png">
<img width="1440" alt="截圖 2022-08-11 下午9 13 00" src="https://user-images.githubusercontent.com/32770959/184273548-4b72c117-5b4f-4382-89db-db64ac187420.png">
<img width="1440" alt="截圖 2022-08-11 下午9 03 41" src="https://user-images.githubusercontent.com/32770959/184273554-52cbb4a8-faad-4ce2-a0e2-a86c061504f8.png">
<img width="1440" alt="截圖 2022-08-11 下午9 01 40" src="https://user-images.githubusercontent.com/32770959/184273559-499a5df2-76a1-4b92-b4b1-a30b2229e241.png">

其實我昨晚就找了一下， 我找到了這些

2022-08-12 03:06 UTC, fengguowudi commented
我是基于acl4ssr的private进行的截取

https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list

这个list中的private地址

2022-08-12 04:24 UTC, IceCodeNew commented
> 我是基于acl4ssr的private进行的截取
> 
> [ACL4SSR/ACL4SSR@`master`/Clash/LocalAreaNetwork.list (raw)](https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list)
> 
> 这个list中的private地址

不能不加验证直接采信第三方项目维护的列表。

2022-08-12 04:25 UTC, IceCodeNew commented
> 其實我昨晚就找了一下， 我找到了這些
> 
> ```
> #Aruba router
> full:instant.arubanetworks.com
> full:setmeup.arubanetworks.com
> ```
> 
> ```
> leike.cc
> miwifi.com
> my.router
> ```

辛苦啦，你提个 PR 吧。这个 credit 应该属于你。