Create PicACG
v2fly/domain-list-community pull request #1099
Opened 2022-08-19 09:48 UTC by rootmelo92118

2022-08-19 10:28 UTC, IceCodeNew requested changes
picacg 存在大量仿冒域名，希望你能提供每个域名的信源供 review 参考。

2022-08-19 12:21 UTC, rootmelo92118 reviewed
<img width="493" alt="截圖 2022-08-19 下午7 17 49" src="https://user-images.githubusercontent.com/32770959/185617031-909e3862-2bcc-4a32-8ccc-2357d36e2199.png">
<img width="478" alt="截圖 2022-08-19 下午7 18 57" src="https://user-images.githubusercontent.com/32770959/185617037-521c10f4-8221-4ab4-80c8-776e8d1a5af9.png">
這兩張圖是官方telegram公告， 以下資料大部分引用於他們， 為了避免造成閱讀困難所以單獨上傳圖片， 而不是在每一個域名下都上傳。

2022-08-19 12:21 UTC, rootmelo92118 commented on data/picacg
> +picacomic.xyz
第四與第五行為官方頻道公布的官方網站。

2022-08-19 12:21 UTC, rootmelo92118 commented on data/picacg
> +picacn.xyz
連線 https://download.picaxiazai.xyz/ 後域名會被重定向至 download.picacn.xyz

2022-08-19 12:21 UTC, rootmelo92118 commented on data/picacg
> +picacg2022.com
<img width="885" alt="截圖 2022-08-19 下午7 22 11" src="https://user-images.githubusercontent.com/32770959/185616837-856f0531-4134-454e-a798-0020b7069482.png">
google搜索的第一項結果。

2022-08-19 12:21 UTC, rootmelo92118 commented on data/picacg
> +bikaios.xyz
官方提供域名

2022-08-20 04:48 UTC, IceCodeNew commented on data/picacg
> +picacg2022.com
这个不能证明是官方的

2022-08-20 04:49 UTC, rootmelo92118 commented on data/picacg
> +picacg2022.com
> 这个不能证明是官方的

好，那我就將其移動到category-porn

2022-08-20 04:55 UTC, IceCodeNew requested changes

2022-08-20 04:55 UTC, IceCodeNew commented on data/picacg
> +regexp:\.bika[a-z]\.xyz$
还剩这个域名没有确认

2022-08-20 05:06 UTC, IceCodeNew commented on data/picacg
> +regexp:\.bika[ac]\.xyz$
1. 你给的截图里我好像找不到这两个域名
2. 只有两个域名的话还是单独列出来吧，没必要正则

2022-08-20 05:06 UTC, rootmelo92118 commented on data/picacg
> +regexp:\.bika[a-z]\.xyz$
這個域名是 http://i.bikaios.xyz/ 在瀏覽器搜索後他會重定向的域名裡面找到的 `ios.bikaa.xyz` 而旁邊的「點我跳轉新域名」則會跳轉至 `ios.bikac.xyz` 這行正則表達式我個人的想法是依照我個人的經驗這種類型的網站後面的字母其實就只是作為一種序號， 被牆了之後就換下一個， 也就是說之後他未來會跑到xyz。 只是為了給未來的維護動作上給予方便而不是一直無限的增加域名行數。

2022-08-20 05:06 UTC, IceCodeNew requested changes
。

2022-08-20 05:11 UTC, rootmelo92118 commented on data/picacg
> +regexp:\.bika[ac]\.xyz$
好， 就照著你說的吧。

2022-08-20 05:12 UTC, IceCodeNew commented on data/picacg
> +regexp:\.bika[a-z]\.xyz$
> 這個域名是 [http://i.bikaios.xyz](http://i.bikaios.xyz/) 在瀏覽器搜索後他會重定向的域名裡面找到的 `ios.bikaa.xyz` 而旁邊的「點我跳轉新域名」則會跳轉至 `ios.bikac.xyz` 這行正則表達式我個人的想法是依照我個人的經驗這種類型的網站後面的字母其實就只是作為一種序號， 被牆了之後就換下一個， 也就是說之後他未來會跑到xyz。 只是為了給未來的維護動作上給予方便而不是一直無限的增加域名行數。 現在我已經將內容修改為`regexp:\.bika[ac]\.xyz$`， 等待未來的擴充

你说的有道理，但是我觉得只有两个域名就下判断认为是这种规律台武断了，可以再观察观察。
现在我倾向于建议你把两条域名单独列出来

2022-08-20 05:13 UTC, IceCodeNew approved these changes

2022-08-20 05:13 UTC, merged

2022-08-20 05:13 UTC, IceCodeNew commented
辛苦啦