Multiple Modifications
v2fly/domain-list-community pull request #1105
Opened 2022-08-21 17:10 UTC by KukiSa

1. Added a DNSPod domain;
2. Added HSTS Preload List domain (operated by Google);
3. Redesigned the domains of Huaweicloud;
4. Added Tencent's domains (粤 B2-20090059, ICPed with the MIIT by Shenzhen Tencent Computer System Co., Ltd.).

2022-08-21 17:40 UTC, KukiSa commented
I found some bugs, please don't merge for now until I have time to work on them.
Regarding some domains that Tencent operates on behalf of, I intend to classify them in the documents of their original holders.

2022-08-21 18:09 UTC, KukiSa commented
把 Roblox 独立了一下，顺便把 NS 的域名还给任天堂了。
其实腾讯运营业务的其实很多，比如枫叶电商平台、Supercell, WeGame, NBA 官方网站之类的应该可以放进对应的分类文件里。
下次有空再弄吧。

2022-08-22 01:17 UTC, IceCodeNew commented
我今天会 review 这个 PR，在此之前请不要合并。

2022-08-22 01:19 UTC, rootmelo92118 commented
> 我今天会 review 这个 PR，在此之前请不要合并。

好，我會基於他提供的內容提出一些疑問或者修改建議。

2022-08-22 01:20 UTC, rootmelo92118 commented on data/google
> +hstspreload.org
<img width="818" alt="截圖 2022-08-22 上午9 19 33" src="https://user-images.githubusercontent.com/32770959/185820957-2ff23d82-e9fd-4be8-ada5-b1a54da072d5.png">
https://github.com/chromium/hstspreload.org 專案中提到，他並不是google官方的產品

2022-08-22 01:27 UTC, rootmelo92118 commented on data/nintendo
> +nintendoswitch.cn
```suggestion
nintendoswitch.cn @cn
```

2022-08-22 01:27 UTC, rootmelo92118 commented on data/nintendo
> +nintendoswitch.com.cn
```suggestion
nintendoswitch.com.cn @cn
```

2022-08-22 01:32 UTC, rootmelo92118 requested changes

2022-08-22 01:32 UTC, rootmelo92118 commented on data/google
> +hstspreload.org
<img width="818" alt="截圖 2022-08-22 上午9 19 33" src="https://user-images.githubusercontent.com/32770959/185821822-cbbc6863-adf7-4728-a862-beb8707256ea.png">
<a href="https://github.com/chromium/hstspreload.org">Repository</a>
專案中提到，他並不是google官方的產品。

2022-08-22 01:32 UTC, rootmelo92118 commented on data/nintendo
> +nintendoswitch.cn
```suggestion
nintendoswitch.cn @cn
```

2022-08-22 01:32 UTC, rootmelo92118 commented on data/nintendo
> +nintendoswitch.com.cn
```suggestion
nintendoswitch.com.cn @cn
```

2022-08-22 02:13 UTC, KukiSa commented on data/google
> +hstspreload.org
这个可以削除，等我有时间看看能否放到其它分类中。

2022-08-22 11:08 UTC, IceCodeNew commented
1. 这个 PR 需要拆分。我可以接受把几项小修改合在一个 PR 里做，但不能接受这里大改腾讯、华为的分类以后还揉些别的内容。
2. 腾讯分类加入的域名太多，超出了可以 review 的范围。
3. 华为云 CDN 相关的域名移动下位置，放在一块吧。

2022-08-22 11:08 UTC, closed without merging

2022-08-22 11:11 UTC, IceCodeNew commented
就现在而言，建议把除了腾讯、华为之外的修改重新提一次 PR（如果还是很大，请提前拆分，不要揉在一块）。  
然后单独为华为、腾讯提 PR。  
感谢你的贡献~

2022-08-22 16:05 UTC, KukiSa commented
> 就现在而言，建议把除了腾讯、华为之外的修改重新提一次 PR（如果还是很大，请提前拆分，不要揉在一块）。 然后单独为华为、腾讯提 PR。 感谢你的贡献~

之前想过发 Issue 提议把各大综合性互联网公司的公有云域名单列出来，后来发现工作量比较大，就单独先做了一下华为云。
至于腾讯的内容我会考虑一下把一些比较主要的业务单列出来再提交。
另外，腾讯云用到的域名比阿里云都复杂，请提前做好心理准备～
感谢您的意见。

2022-08-23 02:08 UTC, IceCodeNew commented
> > 就现在而言，建议把除了腾讯、华为之外的修改重新提一次 PR（如果还是很大，请提前拆分，不要揉在一块）。 然后单独为华为、腾讯提 PR。 感谢你的贡献~
> 
> 之前想过发 Issue 提议把各大综合性互联网公司的公有云域名单列出来，后来发现工作量比较大，就单独先做了一下华为云。 至于腾讯的内容我会考虑一下把一些比较主要的业务单列出来再提交。 另外，腾讯云用到的域名比阿里云都复杂，请提前做好心理准备～ 感谢您的意见。

嗯嗯，提 PR 时尽量站在 review 的角度，尽量让 pr 的信息都能被 reviewer 很好地接受~