Create tencent-games
v2fly/domain-list-community pull request #1132
Opened 2022-08-30 16:14 UTC by KukiSa

`battlecare.net` 战场助手官网 粤B2-20090059-297
`gameitop.com` 海外游戏登录 粤B2-20090059-227
`gameloop.com` gameloop网站 粤B2-20090059-1071
`gcloudcs.com` Apollo游戏云 粤B2-20090059-173
`gcloudcstest.com` 腾讯游戏云 粤B2-20090059-182
`gcloudcstestonly.com` 腾讯游戏服务 粤B2-20090059-207
`gclouddolphin.com` 腾讯游戏服务游戏更新 粤B2-20090059-201
`gcloudsdk.com` 腾讯互娱云sdk专用域名 粤B2-20090059-535
`gdtimg.com` SPA广告素材图片 粤B2-20090059-290
`goto-game.com` gotogame 粤B2-20090059-31
`goto-game.mobi` gotogame 粤B2-20090059-31
`goto-game.net.cn` gotogame 粤B2-20090059-31
`goto-game.org` gotogame 粤B2-20090059-31
`gtgres.com` WG静态资源 粤B2-20090059-370
`happyhlddz.com` 欢乐斗地主国际版 粤B2-20090059-487
`hdyxgame.com` hdyxgame网站 粤B2-20090059-1011
`hkgcloudcs.com` 腾讯游戏服务 粤B2-20090059-199
`ihappystudio.cn` 欢乐游戏工作室 粤B2-20090059-468
`ihappystudio.com` 欢乐游戏工作室 粤B2-20090059-467
`in.th` 天天传奇泰国游戏 粤B2-20090059-234
`ludosuperstar.cn` Ludo世界 粤B2-20090059-540
`ludoworld.net` Ludo世界 粤B2-20090059-541
`mahjongai.net` 麻将AI 粤B2-20090059-357
`mahjongcup.cn` 麻将AI 粤B2-20090059-356
`mahjongcup.com` 麻将AI 粤B2-20090059-356
`mahjongcup.net` 麻将AI 粤B2-20090059-356
`metalrevolution.com` 金属对决官网 粤B2-20090059-431
`midasbuy.com` Mdasbuy网站 粤B2-20090059-478
`nagcloudcs.com` 腾讯游戏服务 粤B2-20090059-226
`openmidas.com` midas开放官网 粤B2-20090059-322
`proximabeta.com` proximabeta网站 粤B2-20090059-422
`pubghelper.com` 游戏助手 粤B2-20090059-278
`pubgno1.cn` Steam中文网 粤B2-20090059-464
`pubgtool.com` 游戏助手 粤B2-20090059-279
`qqgameapp.com` qqgamesapp网站 粤B2-20090059-54
`qqgamedesign.com` qqgame品牌设计规范站 粤B2-20090059-361
`rmwxgame.com` 节奏大师 粤B2-20090059-325
`skydweller.cn` 碧蓝网 粤B2-20090059-1092
`syxlgame.com` syxlgame网站 粤B2-20090059-1021
`tencent-gcloud.com` Gcloud网站 粤B2-20090059-1045
`tencentstart.com` 腾讯Start云 粤B2-20090059-425
`texasholdemcup.cn` 德州扑克AI比赛 粤B2-20090059-340
`texasholdemcup.com` 德州扑克AI比赛 粤B2-20090059-340
`texasholdemcup.net` 德州扑克AI比赛 粤B2-20090059-340
`timibase.com` 天美创新研发基地 粤B2-20090059-1198
`videoxiaoyouxi.com` videoxiaoyouxi网站 粤B2-20090059-520
`wcbygame.com` 王朝霸域 粤B2-20090059-327
`yxdmgame.com` yxdmgame网站 粤B2-20090059-1020
`yximg.cn` 手Q游戏运营开发平台 粤B2-20090059-311
`yxwsgame.com` yxwsgame网站 粤B2-20090059-1019
`yzyxgame.com` yzyxgame网站 粤B2-20090059-1009
`zcjbgame.com` zcjbgame网站 粤B2-20090059-1008
`zhuoyuegame.com` 卓越工坊 粤B2-20090059-1177
`碧蓝幻想.cn` 碧蓝网 粤B2-20090059-1093

## Roblox
`roblox.cn` Roblox网站 粤B2-20090059-463
`robloxdev.cn` 罗布乐思（深圳）数码科技有限公司 粤ICP备20013629号

## NExT Studios
`nextstudios.com` NExTStudios工作室 粤B2-20090059-471
`nextworkshop.net` NExTWorkshop网站 粤B2-20090059-1170

## 迷失之地
`mszdld.cn` mszdld网站 粤B2-20090059-1007
`mszdld.com` mszdld网站 粤B2-20090059-1005
`mszdld.net` mszdld网站 粤B2-20090059-1006

## 篝火营地
`gamebonfire.com` 篝火营地app官网 粤B2-20090059-399

## WeGame
`ffbuddy.com` Wegame海外社区 粤B2-20090059-472
`gotolink.net` wegame海外社区 粤B2-20090059-512
`realcybertron.com` wegame国际版 粤B2-20090059-424
`wegame.com` wegame主页 粤B2-20090059-246
`wegame.com.cn` wegame下载 粤B2-20090059-376
`wegamedeveloper.com` wegame开发者平台 粤B2-20090059-408
`wegameplus.com` WeGame之家 粤B2-20090059-412
`werepository.com.cn` wegame国内版静态资源分发域名 粤B2-20090059-382

## Supercell
`brawlstars.cn` supercell产品国内网站 粤B2-20090059-543
`haydaypop.cn` supercell产品国内网站 粤B2-20090059-1066
`labycore.cn` supercell产品国内网站 粤B2-20090059-1078
`sccreator.cn` supercell国内网站 粤B2-20090059-1052
`sccreators.cn` supercell国内网站 粤B2-20090059-1051
`scescdn.cn` supercell产品国内网站 粤B2-20090059-1140
`scid.cn` supercell产品国内网站 粤B2-20090059-544
`scsentry.cn` supercell国内网站 粤B2-20090059-1050
`supercellcommunity.cn` supercell产品国内网站 粤B2-20090059-1134
`supercellsupport.cn` supercell产品国内网站 粤B2-20090059-545

## 使命召唤
`codm.com` 使命召唤手游官网 粤B2-20090059-443

## 穿越火线
`bcfmglobal.com` 穿越火线手游全球 粤B2-20090059-348
`tcfmglobal.com` 穿越火线手游全球 粤B2-20090059-348

## 腾讯游戏安全专家
`anticheatexpert.com` Anti-cheatExpert网站 粤B2-20090059-449

## 洛克王国
`17roco.com` 洛克王国官网 粤B2-20090059-32
`roco.qq.com`

2022-08-31 00:14 UTC, rootmelo92118 requested changes
`category-games`這個類別被直接包含在`geolocation-!cn`中，而騰訊遊戲中有非常多的域名是在中國大陸所運營的，直接包含進來會導致騰訊遊戲在分流時被走代理，所以在遊戲分類中，中國大陸的遊戲建議都加上`@cn`標籤， 以利下游專案處理，例如：<a href="https://github.com/Loyalsoldier/domain-list-custom">repository</a>

2022-08-31 00:25 UTC, rootmelo92118 commented
如果你覺得這樣子容易混亂的話， 我之前用的是另外一個方法處理米哈遊的分類， 我將該類別一分為二。
<a href="https://github.com/v2fly/domain-list-community/blob/master/data/mihoyo">mihoyo</a>
<a href="https://github.com/v2fly/domain-list-community/blob/master/data/mihoyo-cn">mihoyo-cn</a>
<a href="https://github.com/v2fly/domain-list-community/blob/master/data/hoyoverse">hoyoverse</a>
並將`mihoyo-cn`中的域名打上`@cn`的標籤，最後將`mihoyo`加入`category-games`分類。

2022-08-31 00:25 UTC, rootmelo92118 commented
如果有什麼覺得很奇怪的部分可以標記我。

2022-08-31 07:58 UTC, KukiSa commented
腾讯游戏的产品线过于繁杂，通过腾讯公司主体的 ICP 证拉取的有备案的涉及到腾讯游戏的域名暂时如本 PR 所列。

目前暂且认定有备案的域名正在或将会被解析到中国大陆，因此在第二个 commit 里我将大部分域名均打上了 `@cn`.

2022-08-31 08:00 UTC, rootmelo92118 commented
> 腾讯游戏的产品线过于繁杂，通过腾讯公司主体的 ICP 证拉取的有备案的涉及到腾讯游戏的域名暂时如本 PR 所列。
> 
> 目前暂且认定有备案的域名正在或将会被解析到中国大陆，因此在第二个 commit 里我将大部分域名均打上了 `@cn`.

有些域名你沒有打上的我重新查詢之後發現有ICP所以我也幫你打上了

2022-08-31 08:02 UTC, KukiSa commented
> > 腾讯游戏的产品线过于繁杂，通过腾讯公司主体的 ICP 证拉取的有备案的涉及到腾讯游戏的域名暂时如本 PR 所列。
> > 目前暂且认定有备案的域名正在或将会被解析到中国大陆，因此在第二个 commit 里我将大部分域名均打上了 `@cn`.
> 
> 有些域名你沒有打上的我重新查詢之後發現有ICP所以我也幫你打上了

非常感谢。另外我把缩进符看成换行，实在不好意思

2022-08-31 08:03 UTC, rootmelo92118 commented
> > 腾讯游戏的产品线过于繁杂，通过腾讯公司主体的 ICP 证拉取的有备案的涉及到腾讯游戏的域名暂时如本 PR 所列。
> > 目前暂且认定有备案的域名正在或将会被解析到中国大陆，因此在第二个 commit 里我将大部分域名均打上了 `@cn`.
> 
> 有些域名你沒有打上的我重新查詢之後發現有ICP所以我也幫你打上了

現在需要處理的是`riot` 因為你在騰訊遊戲中引入了他，而他原本已經被引入`category-games`， 勢必要進行移除但是`tencent-games`又會隨著`tencent`被引入`geolocation-cn`， 所以還需要再打其他的標籤。

2022-08-31 08:13 UTC, KukiSa commented
> > > 腾讯游戏的产品线过于繁杂，通过腾讯公司主体的 ICP 证拉取的有备案的涉及到腾讯游戏的域名暂时如本 PR 所列。
> > > 目前暂且认定有备案的域名正在或将会被解析到中国大陆，因此在第二个 commit 里我将大部分域名均打上了 `@cn`.
> > 
> > 
> > 有些域名你沒有打上的我重新查詢之後發現有ICP所以我也幫你打上了
> 
> 現在需要處理的是`riot` 因為你在騰訊遊戲中引入了他，而他原本已經被引入`category-games`， 勢必要進行移除但是`tencent-games`又會隨著`tencent`被引入`geolocation-cn`， 所以還需要再打其他的標籤。當然你也可以選擇將`riot`於`tencent-game`中移除，維持原樣。

我倾向于选择在 `tencent-games` 中移除 `include:riot`，因 `tencent-games` 目前未涵盖一半以上的腾讯游戏的域名。未来有更完整的域名列表的时候再考虑捋清腾讯游戏的子公司域名的文件的组织逻辑。

2022-08-31 08:25 UTC, rootmelo92118 commented
Thanks for your contribution and collaboration！

2022-08-31 08:25 UTC, merged

2023-01-05 07:44 UTC, vrichv commented
@KukiSa  有问题，supercell.com及所有下级域名一般都是使用非中国的亚马逊云，此代码包括了supercell.com，使到geosite:cn内包含了不应该直连的supercell.com，导致链接不稳定引发游戏偶发性断联。请删除此行。

supercell.com
supercellcommunity.cn @cn
supercellsupport.cn @cn
=======================
nslookup supercell.com 114.114.114.114
服务器:  public1.114dns.com
Address:  114.114.114.114
非权威应答:
名称:    supercell.com
Addresses:  13.225.103.54
          13.225.103.56
          13.225.103.71


nslookup supercell.com 223.5.5.5
服务器:  public1.alidns.com
Address:  223.5.5.5
非权威应答:
名称:    supercell.com
Addresses:  54.192.18.98
          54.192.18.95
          54.192.18.120
          54.192.18.115
=================
域名/IP	获取的IP地址	数字地址	IP的物理位置
18.66.122.41	18.66.122.41	306346537	德国黑森法兰克福 亚马逊云
18.66.122.45	18.66.122.45	306346541	德国黑森法兰克福 亚马逊云
18.66.122.57	18.66.122.57	306346553	德国黑森法兰克福 亚马逊云
18.66.122.32	18.66.122.32	306346528	德国黑森法兰克福 亚马逊云
13.33.174.113	13.33.174.113	220311153	法国巴黎 亚马逊云
13.33.174.9	13.33.174.9	220311049	法国巴黎 亚马逊云
143.204.86.50	143.204.86.50	2412533298	日本东京 亚马逊云
143.204.86.78	143.204.86.78	2412533326	日本东京 亚马逊云
13.35.49.49	13.35.49.49	220410161	日本东京 亚马逊云
13.35.49.27	13.35.49.27	220410139	日本东京 亚马逊云
13.33.174.66	13.33.174.66	220311106	法国巴黎 亚马逊云
143.204.215.120	143.204.215.120	2412566392	德国黑森法兰克福 亚马逊云
13.226.225.44	13.226.225.44	232972588	美国加利福尼亚洛杉矶 亚马逊云
13.33.174.117	13.33.174.117	220311157	法国巴黎 亚马逊云
143.204.86.118	143.204.86.118	2412533366	日本东京 亚马逊云
13.35.49.101	13.35.49.101	220410213	日本东京 亚马逊云
143.204.215.46	143.204.215.46	2412566318	德国黑森法兰克福 亚马逊云
143.204.215.13	143.204.215.13	2412566285	德国黑森法兰克福 亚马逊云
13.225.114.27	13.225.114.27	232878619	韩国首尔 亚马逊云
13.225.114.101	13.225.114.101	232878693	韩国首尔 亚马逊云
13.225.114.58	13.225.114.58	232878650	韩国首尔 亚马逊云
13.225.114.89	13.225.114.89	232878681	韩国首尔 亚马逊云
65.9.86.12	65.9.86.12	1091130892	荷兰北荷兰省阿姆斯特丹 亚马逊云
65.9.86.106	65.9.86.106	1091130986	荷兰北荷兰省阿姆斯特丹 亚马逊云
65.9.86.4	65.9.86.4	1091130884	荷兰北荷兰省阿姆斯特丹 亚马逊云
65.9.86.82	65.9.86.82	1091130962	荷兰北荷兰省阿姆斯特丹 亚马逊云
13.226.225.121	13.226.225.121	232972665	美国加利福尼亚洛杉矶 亚马逊云
13.226.225.60	13.226.225.60	232972604	美国加利福尼亚洛杉矶 亚马逊云
13.227.254.80	13.227.254.80	233045584	新加坡 亚马逊云
13.227.254.113	13.227.254.113	233045617	新加坡 亚马逊云
13.227.254.5	13.227.254.5	233045509	新加坡 亚马逊云
54.192.18.120	54.192.18.120	918557304	中国香港 亚马逊云
54.192.18.115	54.192.18.115	918557299	中国香港 亚马逊云
143.204.86.79	143.204.86.79	2412533327	日本东京 亚马逊云
13.224.189.88	13.224.189.88	232832344	德国黑森法兰克福 亚马逊云
13.224.189.29	13.224.189.29	232832285	德国黑森法兰克福 亚马逊云
13.224.189.85	13.224.189.85	232832341	德国黑森法兰克福 亚马逊云
13.35.49.115	13.35.49.115	220410227	日本东京 亚马逊云
13.226.225.52	13.226.225.52	232972596	美国加利福尼亚洛杉矶 亚马逊云
143.204.215.49	143.204.215.49	2412566321	德国黑森法兰克福 亚马逊云
18.160.41.47	18.160.41.47	312486191	美国 亚马逊云
18.160.41.124	18.160.41.124	312486268	美国 亚马逊云
18.160.41.29	18.160.41.29	312486173	美国 亚马逊云
18.160.41.99	18.160.41.99	312486243	美国 亚马逊云
99.86.207.57	99.86.207.57	1666633529	韩国首尔 亚马逊云
99.86.207.69	99.86.207.69	1666633541	韩国首尔 亚马逊云
99.86.207.16	99.86.207.16	1666633488	韩国首尔 亚马逊云
99.86.207.53	99.86.207.53	1666633525	韩国首尔 亚马逊云
13.225.103.71	13.225.103.71	232875847	中国香港 亚马逊云
13.225.103.56	13.225.103.56	232875832	中国香港 亚马逊云
13.225.103.52	13.225.103.52	232875828	中国香港 亚马逊云
65.8.11.128	65.8.11.128	1091046272	马来西亚吉隆坡吉隆坡 亚马逊云
65.8.11.31	65.8.11.31	1091046175	马来西亚吉隆坡吉隆坡 亚马逊云
65.8.11.64	65.8.11.64	1091046208	马来西亚吉隆坡吉隆坡 亚马逊云
54.192.18.95	54.192.18.95	918557279	中国香港 亚马逊云
13.225.142.86	13.225.142.86	232885846	美国加利福尼亚洛杉矶 亚马逊云
13.225.142.75	13.225.142.75	232885835	美国加利福尼亚洛杉矶 亚马逊云
13.225.142.123	13.225.142.123	232885883	美国加利福尼亚洛杉矶 亚马逊云
54.192.18.98	54.192.18.98	918557282	中国香港 亚马逊云
13.35.24.54	13.35.24.54	220403766	中国台湾台北 亚马逊云
13.35.24.99	13.35.24.99	220403811	中国台湾台北 亚马逊云
13.35.24.125	13.35.24.125	220403837	中国台湾台北 亚马逊云
13.227.254.21	13.227.254.21	233045525	新加坡 亚马逊云
18.66.15.5	18.66.15.5	306319109	奥地利维也纳 亚马逊云
18.66.15.2	18.66.15.2	306319106	奥地利维也纳 亚马逊云
18.66.15.122	18.66.15.122	306319226	奥地利维也纳 亚马逊云
18.65.185.20	18.65.185.20	306297108	日本东京 亚马逊云
18.65.185.94	18.65.185.94	306297182	日本东京 亚马逊云
18.65.185.70	18.65.185.70	306297158	日本东京 亚马逊云
18.154.132.83	18.154.132.83	312116307	美国加利福尼亚洛杉矶 亚马逊云
18.154.132.97	18.154.132.97	312116321	美国加利福尼亚洛杉矶 亚马逊云
18.154.132.112	18.154.132.112	312116336	美国加利福尼亚洛杉矶 亚马逊云
18.154.132.46	18.154.132.46	312116270	美国加利福尼亚洛杉矶 亚马逊云
13.224.189.89	13.224.189.89	232832345	德国黑森法兰克福 亚马逊云
13.35.7.90	13.35.7.90	220399450	中国台湾台北 亚马逊云
13.35.7.43	13.35.7.43	220399403	中国台湾台北 亚马逊云
13.35.7.83	13.35.7.83	220399443	中国台湾台北 亚马逊云
13.35.8.6	13.35.8.6	220399622	新加坡 亚马逊云
13.35.8.81	13.35.8.81	220399697	新加坡 亚马逊云
13.35.8.63	13.35.8.63	220399679	新加坡 亚马逊云
13.35.8.126	13.35.8.126	220399742	新加坡 亚马逊云

2023-01-05 07:53 UTC, KukiSa commented
> @KukiSa 代码有问题，supercell.com及所有下级域名一般都是使用非中国的亚马逊云，此代码包括了supercell.com，使到geosite:cn内包含了不应该直连的supercell.com，导致链接不稳定引发游戏偶发性断联。请删除此行。
> 
> supercell.com supercellcommunity.cn @cn supercellsupport.cn @cn
> 
> nslookup supercell.com 114.114.114.114 服务器: public1.114dns.com Address: 114.114.114.114 非权威应答: 名称: supercell.com Addresses: 13.225.103.54 13.225.103.56 13.225.103.71
> 
> nslookup supercell.com 223.5.5.5 服务器: public1.alidns.com Address: 223.5.5.5 非权威应答: 名称: supercell.com Addresses: 54.192.18.98 54.192.18.95 54.192.18.120 54.192.18.115
> 
> 域名/IP 获取的IP地址 数字地址 IP的物理位置 18.66.122.41 18.66.122.41 306346537 德国黑森法兰克福 亚马逊云 18.66.122.45 18.66.122.45 306346541 德国黑森法兰克福 亚马逊云 18.66.122.57 18.66.122.57 306346553 德国黑森法兰克福 亚马逊云 18.66.122.32 18.66.122.32 306346528 德国黑森法兰克福 亚马逊云 13.33.174.113 13.33.174.113 220311153 法国巴黎 亚马逊云 13.33.174.9 13.33.174.9 220311049 法国巴黎 亚马逊云 143.204.86.50 143.204.86.50 2412533298 日本东京 亚马逊云 143.204.86.78 143.204.86.78 2412533326 日本东京 亚马逊云 13.35.49.49 13.35.49.49 220410161 日本东京 亚马逊云 13.35.49.27 13.35.49.27 220410139 日本东京 亚马逊云 13.33.174.66 13.33.174.66 220311106 法国巴黎 亚马逊云 143.204.215.120 143.204.215.120 2412566392 德国黑森法兰克福 亚马逊云 13.226.225.44 13.226.225.44 232972588 美国加利福尼亚洛杉矶 亚马逊云 13.33.174.117 13.33.174.117 220311157 法国巴黎 亚马逊云 143.204.86.118 143.204.86.118 2412533366 日本东京 亚马逊云 13.35.49.101 13.35.49.101 220410213 日本东京 亚马逊云 143.204.215.46 143.204.215.46 2412566318 德国黑森法兰克福 亚马逊云 143.204.215.13 143.204.215.13 2412566285 德国黑森法兰克福 亚马逊云 13.225.114.27 13.225.114.27 232878619 韩国首尔 亚马逊云 13.225.114.101 13.225.114.101 232878693 韩国首尔 亚马逊云 13.225.114.58 13.225.114.58 232878650 韩国首尔 亚马逊云 13.225.114.89 13.225.114.89 232878681 韩国首尔 亚马逊云 65.9.86.12 65.9.86.12 1091130892 荷兰北荷兰省阿姆斯特丹 亚马逊云 65.9.86.106 65.9.86.106 1091130986 荷兰北荷兰省阿姆斯特丹 亚马逊云 65.9.86.4 65.9.86.4 1091130884 荷兰北荷兰省阿姆斯特丹 亚马逊云 65.9.86.82 65.9.86.82 1091130962 荷兰北荷兰省阿姆斯特丹 亚马逊云 13.226.225.121 13.226.225.121 232972665 美国加利福尼亚洛杉矶 亚马逊云 13.226.225.60 13.226.225.60 232972604 美国加利福尼亚洛杉矶 亚马逊云 13.227.254.80 13.227.254.80 233045584 新加坡 亚马逊云 13.227.254.113 13.227.254.113 233045617 新加坡 亚马逊云 13.227.254.5 13.227.254.5 233045509 新加坡 亚马逊云 54.192.18.120 54.192.18.120 918557304 中国香港 亚马逊云 54.192.18.115 54.192.18.115 918557299 中国香港 亚马逊云 143.204.86.79 143.204.86.79 2412533327 日本东京 亚马逊云 13.224.189.88 13.224.189.88 232832344 德国黑森法兰克福 亚马逊云 13.224.189.29 13.224.189.29 232832285 德国黑森法兰克福 亚马逊云 13.224.189.85 13.224.189.85 232832341 德国黑森法兰克福 亚马逊云 13.35.49.115 13.35.49.115 220410227 日本东京 亚马逊云 13.226.225.52 13.226.225.52 232972596 美国加利福尼亚洛杉矶 亚马逊云 143.204.215.49 143.204.215.49 2412566321 德国黑森法兰克福 亚马逊云 18.160.41.47 18.160.41.47 312486191 美国 亚马逊云 18.160.41.124 18.160.41.124 312486268 美国 亚马逊云 18.160.41.29 18.160.41.29 312486173 美国 亚马逊云 18.160.41.99 18.160.41.99 312486243 美国 亚马逊云 99.86.207.57 99.86.207.57 1666633529 韩国首尔 亚马逊云 99.86.207.69 99.86.207.69 1666633541 韩国首尔 亚马逊云 99.86.207.16 99.86.207.16 1666633488 韩国首尔 亚马逊云 99.86.207.53 99.86.207.53 1666633525 韩国首尔 亚马逊云 13.225.103.71 13.225.103.71 232875847 中国香港 亚马逊云 13.225.103.56 13.225.103.56 232875832 中国香港 亚马逊云 13.225.103.52 13.225.103.52 232875828 中国香港 亚马逊云 65.8.11.128 65.8.11.128 1091046272 马来西亚吉隆坡吉隆坡 亚马逊云 65.8.11.31 65.8.11.31 1091046175 马来西亚吉隆坡吉隆坡 亚马逊云 65.8.11.64 65.8.11.64 1091046208 马来西亚吉隆坡吉隆坡 亚马逊云 54.192.18.95 54.192.18.95 918557279 中国香港 亚马逊云 13.225.142.86 13.225.142.86 232885846 美国加利福尼亚洛杉矶 亚马逊云 13.225.142.75 13.225.142.75 232885835 美国加利福尼亚洛杉矶 亚马逊云 13.225.142.123 13.225.142.123 232885883 美国加利福尼亚洛杉矶 亚马逊云 54.192.18.98 54.192.18.98 918557282 中国香港 亚马逊云 13.35.24.54 13.35.24.54 220403766 中国台湾台北 亚马逊云 13.35.24.99 13.35.24.99 220403811 中国台湾台北 亚马逊云 13.35.24.125 13.35.24.125 220403837 中国台湾台北 亚马逊云 13.227.254.21 13.227.254.21 233045525 新加坡 亚马逊云 18.66.15.5 18.66.15.5 306319109 奥地利维也纳 亚马逊云 18.66.15.2 18.66.15.2 306319106 奥地利维也纳 亚马逊云 18.66.15.122 18.66.15.122 306319226 奥地利维也纳 亚马逊云 18.65.185.20 18.65.185.20 306297108 日本东京 亚马逊云 18.65.185.94 18.65.185.94 306297182 日本东京 亚马逊云 18.65.185.70 18.65.185.70 306297158 日本东京 亚马逊云 18.154.132.83 18.154.132.83 312116307 美国加利福尼亚洛杉矶 亚马逊云 18.154.132.97 18.154.132.97 312116321 美国加利福尼亚洛杉矶 亚马逊云 18.154.132.112 18.154.132.112 312116336 美国加利福尼亚洛杉矶 亚马逊云 18.154.132.46 18.154.132.46 312116270 美国加利福尼亚洛杉矶 亚马逊云 13.224.189.89 13.224.189.89 232832345 德国黑森法兰克福 亚马逊云 13.35.7.90 13.35.7.90 220399450 中国台湾台北 亚马逊云 13.35.7.43 13.35.7.43 220399403 中国台湾台北 亚马逊云 13.35.7.83 13.35.7.83 220399443 中国台湾台北 亚马逊云 13.35.8.6 13.35.8.6 220399622 新加坡 亚马逊云 13.35.8.81 13.35.8.81 220399697 新加坡 亚马逊云 13.35.8.63 13.35.8.63 220399679 新加坡 亚马逊云 13.35.8.126 13.35.8.126 220399742 新加坡 亚马逊云

`supercell.com` 不包含在 `tencent` 和 `tencent-games` 中，无需删除。