Update qcloud
v2fly/domain-list-community pull request #1172
Opened 2022-09-13 14:02 UTC by KukiSa

1. 删除了解析至中国大陆的 `myqcloud.com` 子域名，因其匹配过于麻烦，例如 `bilibili-ap-shanghai.mycloud.com` 及 `ap-guangzhou-2.myqcloud.com`，其中 `bilibili-` 和 `-2` 处于随时变化的情况之中。
2. 增加了对 `tencentcos.cn`, `tencentcos.com` 和 `tencentcos.com.cn` 的匹配；
3. 增加了 `intltencentcos.com`.

ref:
1. https://crt.sh/?id=6738702126
2. https://crt.sh/?id=6520056666

2022-09-13 14:09 UTC, KukiSa commented
关于 `intltencentcos.com`，参考 https://crt.sh/?id=6263281001.

2022-09-14 00:45 UTC, rootmelo92118 commented
> 1. 删除了解析至中国大陆的 `myqcloud.com` 子域名，因其匹配过于麻烦，例如 `bilibili-ap-shanghai.mycloud.com` 及 `ap-guangzhou-2.myqcloud.com`，其中 `bilibili-` 和 `-2` 处于随时变化的情况之中。
> 2. 增加了对 `tencentcos.cn`, `tencentcos.com` 和 `tencentcos.com.cn` 的匹配；
> 3. 增加了 `intltencentcos.com`.
> 
> ref:
> 
> 1. https://crt.sh/?id=6738702126
> 2. https://crt.sh/?id=6520056666

只要地名能夠固定，我認為可以使用正則表達式來進行匹配。

2022-09-14 00:52 UTC, rootmelo92118 commented on data/qcloud
> +myqcloud.com
在這裡加入該域名，分流不當會導致下面與其相關的境外域名進行直連。

2022-09-14 01:07 UTC, rootmelo92118 requested changes

2022-09-14 01:07 UTC, rootmelo92118 commented on data/qcloud
> +# COS 使用到的非中国大陆的地域与可用区，参见 https://cloud.tencent.com/document/product/436/6224
```suggestion
# COS 使用到的非中国大陆的地域与可用区，参见 https://cloud.tencent.com/document/product/436/6224
regexp:\.(.+-)?ap-beijing(-.+)?\.myqcloud\.com$             #北京
regexp:\.(.+-)?ap-nanjing(-.+)?\.myqcloud\.com$             #南京
regexp:\.(.+-)?ap-shanghai(-.+)?\.myqcloud\.com$            #上海
regexp:\.(.+-)?ap-guangzhou(-.+)?\.myqcloud\.com$           #广州
regexp:\.(.+-)?ap-chengdu(-.+)?\.myqcloud\.com$             #成都
regexp:\.(.+-)?ap-chongqing(-.+)?\.myqcloud\.com$           #重庆
regexp:\.(.+-)?ap-shenzhen(-.+)?\.myqcloud\.com$            #深圳
```

2022-09-14 06:19 UTC, KukiSa commented
> > 1. 删除了解析至中国大陆的 `myqcloud.com` 子域名，因其匹配过于麻烦，例如 `bilibili-ap-shanghai.mycloud.com` 及 `ap-guangzhou-2.myqcloud.com`，其中 `bilibili-` 和 `-2` 处于随时变化的情况之中。
> > 2. 增加了对 `tencentcos.cn`, `tencentcos.com` 和 `tencentcos.com.cn` 的匹配；
> > 3. 增加了 `intltencentcos.com`.
> > 
> > ref:
> > 
> > 1. https://crt.sh/?id=6738702126
> > 2. https://crt.sh/?id=6520056666
> 
> 只要地名能夠固定，我認為可以使用正則表達式來進行匹配。這部分要進行修改的話，可能需要一併更動qcloud海外域名。

海外的地域未观察到有前缀或后缀表示方式。

另，`mycloud.com` 项下还有诸如 `cdn.mycloud.com` 和 `clb.mycloud.com` 等域名集且暂时未找到足以区分地理位置的规律，因此考虑将其 apex name `mycloud.com` 列入，默认其为 `cn`，再通过单列 COS 使用到的 `!cn` 域名以区分。

2022-09-14 06:22 UTC, merged

2022-09-14 06:26 UTC, KukiSa commented on data/qcloud
> +myqcloud.com
> 在這裡加入該域名，分流不當會導致下面與其相關的境外域名進行直連。

目前只观察到 COS 会显性使用 `myqcloud.com` 作为传输层 (TLS SNI) 和应用层 (HTTP Host) 的标记，其他使用到的 `myqcloud.com`几乎均为 DNS CNAME，在透过 v2ray 路由时不会被捕获到或因上层的实际域名被其他规则捕获到，因此以目前的方案仅分流 `myqcloud.com` 海外没什么问题。

2022-09-19 13:15 UTC, IceCodeNew commented
> 1. 删除了解析至中国大陆的 `myqcloud.com` 子域名，因其匹配过于麻烦，例如 `bilibili-ap-shanghai.mycloud.com` 及 `ap-guangzhou-2.myqcloud.com`，其中 `bilibili-` 和 `-2` 处于随时变化的情况之中。

这个项目不完全是为了下游代理路由匹配使用的，之前单独列出的解析到中国的 `myqcloud.com` 子域名希望能继续维护（太麻烦的匹配可以考虑引入正则）