Update geolocation-cn
v2fly/domain-list-community pull request #1189
Opened 2022-09-19 14:44 UTC by rootmelo92118

2022-09-19 15:38 UTC, IceCodeNew requested changes

2022-09-19 15:38 UTC, IceCodeNew commented on data/category-social-media-cn
> +include:douban
排序。

2022-09-19 15:38 UTC, IceCodeNew commented on data/geolocation-cn
> -
这个空行希望能保留，include 和实际域名之间希望能隔开。

2022-09-19 15:38 UTC, IceCodeNew commented
> @IceCodeNew @ma-ji  我恢復了該列表，並對內容進行篩選，僅保留目前有共識的部分。讓其未來有擴充空間。

赞

2022-09-20 00:55 UTC, rootmelo92118 commented on data/geolocation-cn
> -
可以， 但為了列表中排序規則的一致性， 我也會對該列表中其他`include`與域名之間進行區隔。

2022-09-20 14:32 UTC, merged