更新
v2fly/domain-list-community pull request #1200
Opened 2022-09-22 05:05 UTC by HeyBroWhatsUp

2022-09-22 06:21 UTC, rootmelo92118 commented
`geolocation-cn`中未分類域名為歷史遺留問題，不宜再增加。建議進行分類。

2022-09-22 07:17 UTC, IceCodeNew reviewed
删除的这几个无法访问的域名，依据是这些域名都被收回了吗？
否则你需要确定这些域名下所有子域名都不能被访问了。

2022-09-22 08:48 UTC, rootmelo92118 commented
> 删除的这几个无法访问的域名，依据是这些域名都被收回了吗？ 否则你需要确定这些域名下所有子域名都不能被访问了。

第一個是重複，第二個未備案而被阻斷，第三個是其賭博性質及未標示備案號，我認為三個被移除都很合理。

2022-09-22 10:37 UTC, IceCodeNew commented
仍然等待贡献者对新增域名进行分类，有两种方式可以选择：  
  
1. 在 `category-xxx-cn` 子类下添加域名，有必要的话可以新建这样的子类
e.g. https://github.com/v2fly/domain-list-community/pull/1189/  
  
2. 在 `geolocation-cn` 分类下添加域名，但是通过注释注明网站用途，并将相似用途的网站归在一起
e.g. https://github.com/v2fly/domain-list-community/blob/0bda2156c50d3d91d408150fc760407bb68c2efe/data/geolocation-cn#L125-L129

2022-09-22 14:06 UTC, rootmelo92118 commented
@IceCodeNew Github action 沒有效驗這個PR，可能需要注意一下。

2022-09-23 02:08 UTC, IceCodeNew commented
> @IceCodeNew Github action 沒有效驗這個PR，可能需要注意一下。

是因为文件有冲突了
@HeyBroWhatsUp 方便 git rebase 吗？如果不会操作可以等我晚上来处理。

2022-09-23 03:13 UTC, HeyBroWhatsUp commented
好了

2022-09-23 03:20 UTC, HeyBroWhatsUp commented
好了

2022-09-23 04:07 UTC, IceCodeNew requested changes

2022-09-23 04:07 UTC, IceCodeNew commented on data/geolocation-cn
> +itdog.cn #itdog网站工具箱
```suggestion
# 在线工具
itdog.cn # itdog网站工具箱
```

2022-09-23 04:07 UTC, IceCodeNew commented on data/geolocation-cn
> +include:ipip
```suggestion
# IP 定位网站
include:ipip

```

2022-09-23 04:07 UTC, IceCodeNew commented on data/geolocation-cn
> +admin5.com
待分类

2022-09-23 04:07 UTC, IceCodeNew commented on data/geolocation-cn
> +idcquan.com
待分类

2022-09-23 04:10 UTC, IceCodeNew commented on data/geolocation-cn
> -expreview.com
这个域名为什么要删除？

2022-09-23 04:10 UTC, IceCodeNew commented on data/geolocation-cn
> -fyxz.com
重复，可删

2022-09-23 04:10 UTC, IceCodeNew commented on data/geolocation-cn
> -genelinkout.com
未备案被墙

2022-09-23 04:10 UTC, IceCodeNew commented on data/geolocation-cn
> -gmallbio.com
赌博性质、未标示备案号

2022-09-23 06:25 UTC, HeyBroWhatsUp commented on data/geolocation-cn
> -expreview.com
不会用rebase，reset后忘记弄了。。。

2022-09-23 07:16 UTC, IceCodeNew approved these changes

2022-09-23 07:17 UTC, merged