Update boc, ccb, cmb, icbc and unionpay
v2fly/domain-list-community pull request #1205
Opened 2022-09-22 13:42 UTC by KukiSa

## 中国银行股份有限公司 京ICP备10052455号
`bank-of-china.com` 京ICP备10052455号-1
`bocfullertonbank.com` 京ICP备10052455号-2

## 中银消费金融有限公司 沪ICP备10203561号
`boccfc.cc` 沪ICP备10203561号-2

## 中银国际证券股份有限公司 沪ICP备08011679号
`bocichina.cn` 沪ICP备08011679号-3
`bocichina.com.cn` 沪ICP备08011679号-3
`bocifunds.cn` 沪ICP备08011679号-4
`bocifunds.com` 沪ICP备08011679号-4
`bocifunds.com.cn` 沪ICP备08011679号-4

## 中银基金管理有限公司 沪ICP备05007423号
`bocamchina.com` 沪ICP备05007423号-4

## 中国建设银行股份有限公司 京ICP备13030780号
`ccb.com.cn` 京ICP备13030780号-1
`ccb.cn` 京ICP备13030780号-1
`ccbcos.com` 京ICP备13030780号-3

## 建信人寿保险股份有限公司 沪ICP备17044175号
`ccblife-test.com.cn` 沪ICP备17044175号-2

## 建信基金管理有限责任公司 京ICP备06004599号
`ccbfund.com.cn` 京ICP备06004599号-1
`ccbfund.com` 京ICP备06004599号-1

## 建信期货有限责任公司 沪ICP备13025333号
`ccbfutures.cn` 沪ICP备13025333号-2

## 建信信托有限责任公司 皖ICP备09023351号
`ccbxt.com` 皖ICP备09023351号-2

## 招商信诺人寿保险有限公司 粤ICP备11053445号
`cignacmb-ipmi.com` 粤ICP备11053445号-2
`test-cignacmb.com` 粤ICP备11053445号-4
`cignacmbamc.com` 粤ICP备11053445号-5

## 招商银行股份有限公司 粤ICP备17088997号
`8008205555.cn` 粤ICP备17088997号-1
`8008205555.com` 粤ICP备17088997号-1
`cmbt.cn` 粤ICP备17088997号-1
`cmburl.cn` 粤ICP备17088997号-1
`cmbchina.biz` 粤ICP备17088997号-2
`cmbuat.com` 粤ICP备17088997号-3
`cmbchina.cn` 粤ICP备17088997号-4
`cmbimg.cn` 粤ICP备17088997号-5

## 招商基金管理有限公司 粤ICP备12081567号
`cmf.ltd` 粤ICP备12081567号-4
`cmfunds.cn` 粤ICP备12081567号-5
`cmf.biz` 粤ICP备12081567号-6

## 中国工商银行股份有限公司 京ICP证030247号
`95588.com.cn` 京ICP证030247号-1
`icbc.com.cn` 京ICP证030247号-1
`icbc-ltd.com` 京ICP证030247号-2
`icbcmy.com` 京ICP证030247号-3
`icbcit.com` 京ICP证030247号-4
`95588.com` 京ICP证030247号-5
`icbcina.com` 京ICP证030247号-6
`icbkus.com` 京ICP证030247号-8
`dccnet.com.cn` 京ICP证030247号-9
`icbkfs.com` 京ICP证030247号-10
`icbc-us.com` 京ICP证030247号-11
`icbcnz.com` 京ICP证030247号-12
`icbcpl.com` 京ICP证030247号-13
`icbcindia.com` 京ICP证030247号-14
`icbc-at.com` 京ICP证030247号-15
`icbcswiss.com` 京ICP证030247号-16
`icbc.co.kr` 京ICP证030247号-17
`icbc.de` 京ICP证030247号-18
`icbc.ae` 京ICP证030247号-19
`icbc.com.vn` 京ICP证030247号-20
`icbcme.ae` 京ICP证030247号-21
`icbc.com.sg` 京ICP证030247号-22
`icbc.co.jp` 京ICP证030247号-23
`icbcmanila.com.cn` 京ICP证030247号-24
`icbc.be` 京ICP证030247号-25
`icbc.eu` 京ICP证030247号-26
`icbcmoscow.ru` 京ICP证030247号-27
`icbc.lu` 京ICP证030247号-28
`icbcparis.fr` 京ICP证030247号-29
`icbcbr.com.br` 京ICP证030247号-30
`icbc.com.au` 京ICP证030247号-31
`icbcthai.com` 京ICP证030247号-32
`icbclondon.com` 京ICP证030247号-33
`icbc.com.qa` 京ICP证030247号-34
`icbc.co.id` 京ICP证030247号-35
`icbc.com.mo` 京ICP证030247号-36
`icbc.com.pk` 京ICP证030247号-37
`icbc.com.kh` 京ICP证030247号-38
`icbc.com.la` 京ICP证030247号-39
`icbc.com.kw` 京ICP证030247号-40
`icbc.com.mm` 京ICP证030247号-41
`icbc.co.nl` 京ICP证030247号-42
`icbc.com.es` 京ICP证030247号-43
`icbc.com.mx` 京ICP证030247号-44
`icbcasia.com` 京ICP证030247号-45
`icbc-cz.com` 京ICP证030247号-46
`icbci.com.hk` 京ICP证030247号-47
`icbc.com.pe` 京ICP证030247号-48
`icbcalmaty.kz` 京ICP证030247号-49
`nic.icbc` 京ICP证030247号-50
`icbc-uk.com` 京ICP证030247号-51
`icbcstandardsecurities.com` 京ICP证030247号-52
`icbcstandardresources.com` 京ICP证030247号-53
`icbcpanama.com` 京ICP证030247号-54
`icbcstandard.com` 京ICP证030247号-55
`icbcstandardbank.com` 京ICP证030247号-56

## 工银瑞信基金管理有限公司 京ICP备05063708号
`icbccstz.com.cn` 京ICP备05063708号-2

## 中国银联股份有限公司 沪ICP备07032180号
`chinaunionpay.com.cn` 沪ICP备07032180号-2
`unionpay.com` 沪ICP备07032180号-2
`unionpaysecure.com` 沪ICP备07032180号-6
`95516.net` 沪ICP备07032180号-9
`chinaunionpay.com` 沪ICP备07032180号-10
`95516.com` 沪ICP备07032180号-11
`chinaunionpay.net` 沪ICP备07032180号-12
`unionpay.net` 沪ICP备07032180号-13
`cup62.cn` 沪ICP备07032180号-14
`cup.com.cn` 沪ICP备07032180号-15

## 银联国际有限公司 沪ICP备13042962号
`unionpayintl.cn` 沪ICP备13042962号-2

2022-09-23 01:44 UTC, IceCodeNew commented on data/boc
> -# Global service
为何取消 Global service 分类？

2022-09-23 02:14 UTC, IceCodeNew commented on data/boc
> -# Global service
> > 为何取消 Global service 分类？
> 
> 该分类无特殊意义。

为什么这么说？中国银行应该有国际业务吧。

2022-09-23 02:47 UTC, KukiSa commented on data/boc
> -# Global service
> > > 为何取消 Global service 分类？
> > 
> > 
> > 该分类无特殊意义。
> 
> 为什么这么说？中国银行应该有国际业务吧。

因为把 `bank-of-china.com` 分类为国际还是不国际我嫌麻烦

2022-09-23 03:33 UTC, IceCodeNew commented on data/boc
> -# Global service
> 因为把 `bank-of-china.com` 分类为国际还是不国际我嫌麻烦

不能因为这种理由直接删除分类吧（
最坏的情况，你可以把 PR 标记为草稿状态，请其他人帮你确认域名到底是否符合分类。

或者给出一个更有力的理由说明我们应该删除这个分类

2022-09-23 03:34 UTC, IceCodeNew requested changes
this PR is not ready.

2022-09-23 04:47 UTC, KukiSa commented on data/boc
> -# Global service
> > 因为把 `bank-of-china.com` 分类为国际还是不国际我嫌麻烦
> 
> 不能因为这种理由直接删除分类吧（ 最坏的情况，你可以把 PR 标记为草稿状态，请其他人帮你确认域名到底是否符合分类。
> 
> 或者给出一个更有力的理由说明我们应该删除这个分类

首先我为今早的不理性和主观性强的解释向大家道歉。
上午 10 时同步的 [commit 3](https://github.com/v2fly/domain-list-community/pull/1205/commits/d45283a3b56cd2b180ff06048f5bbff3f735e5ae) 已经对 PR 进行了与原有形制一致的修正。

对于最初删除 `Global Services` 分类的行为，我的理由如下：
1. `boc.cn`, `bank-of-china.com` 和 `bankofchina.com` 均为中国银行的银行业务域名；
2. 上述三条域名均位于 `boc` 文件中，对文件内 `Global Services` 分类标签的删减不影响旧有状况的实际路由；
3. 其他 (`ccb`, `cmb`, `icbc`) 均没有对 `Global Services` 进行特别分类。

再次表示抱歉，同时希望社区积极对我的行为进行监督与批评。

2022-09-23 07:23 UTC, IceCodeNew commented on data/boc
> -# Global service
没事没事……不用这么严肃

2022-09-23 07:30 UTC, IceCodeNew reviewed
这个 PR 还需要更多熟悉银行业务的人来 review

2022-09-23 07:39 UTC, rootmelo92118 commented
> 这个 PR 还需要更多熟悉银行业务的人来 review

具體是什麼地方有問題？

2022-09-23 13:32 UTC, KukiSa commented
> 这个 PR 还需要更多熟悉银行业务的人来 review

目前应该没有什么需要特别审计的内容。
新增条目均为原有条目所属的主体的其他项下的备案域名，归属权证明完备。
除 `unionpay` 外其他文件的条目的组织形式均未改动，在技术上不会对已有配置产生影响。

2022-09-23 14:50 UTC, IceCodeNew commented
好的，我知道了。
我想明天再来仔细检查一遍，麻烦等我明天来合并吧。

2022-09-24 14:46 UTC, IceCodeNew approved these changes

2022-09-24 14:46 UTC, merged