Update category-porn
v2fly/domain-list-community pull request #1247
Opened 2022-10-12 06:42 UTC by rootmelo92118

Source : [https://www.tcrc.edu.tw/dnsrpz/information-security/dnsrpz](https://www.tcrc.edu.tw/dnsrpz/information-security/dnsrpz) [https://chopper.nchu.edu.tw:10003/d/s/mGkNSHg6eiC39iTGJoGous6UxxhsxEhr/2Vv6D4-_ItnVu3ijzWYIt6CLGKusyB-G-lr1g84-CEQk#file_id=653791487391218101](https://chopper.nchu.edu.tw:10003/d/s/mGkNSHg6eiC39iTGJoGous6UxxhsxEhr/2Vv6D4-_ItnVu3ijzWYIt6CLGKusyB-G-lr1g84-CEQk#file_id=653791487391218101)
This website and its document are belonging to the government of the Republic of China, so I think it can be trusted.
[內政部警政署偵辦違反兒童及少年性剝削防制條例刑案之非法網址(域)彙整表.ods](https://github.com/v2fly/domain-list-community/files/9762214/default.ods)

2022-10-12 10:32 UTC, IceCodeNew commented
https://github.com/v2fly/domain-list-community/pull/1011#discussion_r922966913

这个 PR 会违反我们此前达成的共识吗？我只能接受你参考这个列表从项目中移除涉及儿童及少年性剥削内容的网站。

2022-10-12 10:33 UTC, IceCodeNew requested changes
参见上文。

2022-10-12 14:22 UTC, rootmelo92118 commented
> [#1011 (comment)](https://github.com/v2fly/domain-list-community/pull/1011#discussion_r922966913)
> 
> 这个 PR 会违反我们此前达成的共识吗？我只能接受你参考这个列表从项目中移除涉及儿童及少年性剥削内容的网站。

目前我在網站中似乎沒有尋找到相關內容。

2022-10-12 14:40 UTC, IceCodeNew commented
> 目前我在網站中似乎沒有尋找到相關內容，而依照網頁介面來判斷，這些域名都指向同一個網站。 所以如果你不放心想要看的話其實針對一個來看就可以了。

我明天可以去做这个验证。但是我最近都很忙，所以我的建议是你参照那个涉嫌儿童色情或相关内容的列表直接把对应的域名删掉
因为自己去网站上查看内容是很不精确的方法，很可能会漏掉
而你提供的那个列表我看了下，觉得确实可以拿来参考

// 如果你要添加的域名不是从这个列表里抄来的，我建议你另外开一个 pr。这个 pr 专门用来删除涉嫌儿童色情的内容。

2022-10-12 15:14 UTC, rootmelo92118 commented
> > 目前我在網站中似乎沒有尋找到相關內容，而依照網頁介面來判斷，這些域名都指向同一個網站。 所以如果你不放心想要看的話其實針對一個來看就可以了。
> 
> 我明天可以去做这个验证。但是我最近都很忙，所以我的建议是你参照那个涉嫌儿童色情或相关内容的列表直接把对应的域名删掉 因为自己去网站上查看内容是很不精确的方法，很可能会漏掉 而你提供的那个列表我看了下，觉得确实可以拿来参考
> 
> // 如果你要添加的域名不是从这个列表里抄来的，我建议你另外开一个 pr。这个 pr 专门用来删除涉嫌儿童色情的内容。

好，依據列表內容，目前刪除了一個域名。

2022-10-13 03:58 UTC, IceCodeNew approved these changes

2022-10-13 03:58 UTC, merged