Add hotstar
v2fly/domain-list-community pull request #1253
Opened 2022-10-14 15:25 UTC by guaguaya66

添加 [hotstar](hoststar.com) 域名

2022-10-14 15:45 UTC, rootmelo92118 commented
請下次合併後刪除分支，不然他會出現你上一次的更改紀錄。

2022-10-14 15:49 UTC, guaguaya66 commented
> 請下次合併後刪除分支，不然他會出現你上一次的更改紀錄。 以及我認為可以將其引用至`disney`中。

好的，也可以引用至disney

2022-10-14 15:50 UTC, rootmelo92118 approved these changes

2022-10-14 15:50 UTC, merged

2022-10-15 05:25 UTC, IceCodeNew requested changes

2022-10-15 05:25 UTC, IceCodeNew commented on data/disney
> +
这个空行是怎么回事？pr 没有完成吧
@guaguaya66 @rootmelo92118

2022-10-15 05:25 UTC, IceCodeNew commented on data/hotstar
> +regexp:^hses[1-7]?.akamaized.net$|^hses\s?.akamaized.net$
这个地方应该写成两条记录