Add china's website that can be connected directly
v2fly/domain-list-community pull request #1342
Opened 2022-12-05 11:02 UTC by yunxi993

2022-12-05 16:11 UTC, IceCodeNew requested changes
<img width="886" alt="image" src="https://user-images.githubusercontent.com/32576256/205685488-5713e69e-ea65-4bf3-8b8a-05636c5f0300.png">
<img width="855" alt="image" src="https://user-images.githubusercontent.com/32576256/205685540-a35cc527-47fb-4b35-8dac-eb29aabd0429.png">

你提交的这两条域名看起来都是应城的信息门户网站，希望能把这两条域名放在一块加上注释。
现在的 `geolocation-cn` 分类太臃肿了。不希望未来新的提交还是没有注释没有分类继续往上堆。

2022-12-06 05:56 UTC, IceCodeNew commented
> > 你提交的这两条域名看起来都是应城的信息门户网站，希望能把这两条域名放在一块加上注释。 现在的 `geolocation-cn` 分类太臃肿了。不希望未来新的提交还是没有注释没有分类继续往上堆。
> 
> 不太清楚，群友让帮忙pr的.
> 
> 那么请问我需要创建新的分类吗？
> 
> 该如何注释?

@yunxi993 可以参考下我刚刚的提交

2022-12-06 05:56 UTC, IceCodeNew approved these changes

2022-12-06 05:56 UTC, merged

2022-12-06 10:29 UTC, yunxi993 commented
> @yunxi993 可以参考下我刚刚的提交 [f2d0ae5](https://github.com/v2fly/domain-list-community/pull/1342/commits/f2d0ae5d9da6664b22141bc8b7713100f6f15a2d)

@IceCodeNew 受教了，谢谢!
![image](https://user-images.githubusercontent.com/59167936/205886667-71edcb98-a23e-426a-91b1-4cd5f78f0440.png)

话说，门户网站全部分类到这个下面应该也可以.

2022-12-06 13:32 UTC, yunxi993 commented
> 
> 这里的「门户网站」和这次分类的两个网站的内容偏向不太符合。我也没想到更好的名称


我去这两个网站看了一下，属于面向本地的各类信息融媒体、或许开个全国地方融媒体的标签.