Create decryptipastore
v2fly/domain-list-community pull request #1349
Opened 2022-12-07 01:01 UTC by rootmelo92118

2022-12-07 08:30 UTC, rootmelo92118 commented
> 我反对将 `category-android-app-download` 更名为 `category-app-download`
> app 并不是 android app 的特指，这样更名会改变集合的性质，对之前在使用这个集合（如果有的话）的用户造成影响

我將其修改為`category-mobile-app-download`，這稍微改變合輯的性質，但不致混亂，其原因為引入IOS應用程序安裝包的網站。

2022-12-07 11:31 UTC, IceCodeNew commented
> 我將其修改為`category-mobile-app-download`，這稍微改變合輯的性質，但不致混亂，其原因為引入IOS應用程序安裝包的網站。

我觉得为了单独一个网站去改变一个现存集合的名称是不划算的。而且考虑到未来可能有新的域名加进来，单独列一个 ios 的分类也不错。

2022-12-07 11:32 UTC, IceCodeNew commented on data/decryptipastore
> +dyp.li
@rootmelo92118 这个域名打算如何处理？

2022-12-07 11:33 UTC, rootmelo92118 commented on data/decryptipastore
> +dyp.li
這個短鏈結是專屬於decrypt.day使用的

2022-12-08 03:00 UTC, IceCodeNew commented on data/decryptipastore
> +dyp.li
> 這個短鏈結是專屬於decrypt.day使用的

contact 那边说的是可以申请服务，我觉得并不是专属于 decrypt.day

2022-12-09 01:43 UTC, IceCodeNew requested changes

2022-12-09 01:43 UTC, IceCodeNew commented on data/decryptipastore
> +dyp.li
@rootmelo92118

2022-12-09 01:43 UTC, IceCodeNew commented on data/geolocation-!cn
> +include:decryptipastore
这个和 android 的列表整理放一块吧，然后加个 ios 注释
示例：
```
# Services & Softwares
include:category-android-app-download
include:decryptipastore  # iOS

include:category-browser-!cn
```

2022-12-09 02:15 UTC, IceCodeNew approved these changes

2022-12-09 02:15 UTC, merged