add Addition of other Iranian domains
v2fly/domain-list-community pull request #1368
Opened 2022-12-23 10:39 UTC by alirezax5

I made some changes on Iranian domains for better classification:
Added :

-category-ir-appsandgame
-category-ir-soical
-category-ir-porn
-category-ir-vod
-category-ir-ispAndDatacenter
-category-ir-game
Update :

-category-ir
-category-ir-media
-category-porn

2022-12-23 17:02 UTC, rootmelo92118 commented
Do not do the same operation to PR the next time. It looks like you deleted all contents in one file and submit the new data including the original contents. It will make it difficult for maintainers to read your submissions. Just submit the new addition or modification you want.

2022-12-23 17:04 UTC, rootmelo92118 commented
And sort your data after your modifications.

2022-12-29 17:13 UTC, rootmelo92118 commented
And this PR has conflict in `category-porn`. Rebase it.

2022-12-30 02:15 UTC, IceCodeNew requested changes
> And this PR has conflict in `category-porn`. Rebase it.

@alirezax5 there are 4,632 additions & exact 4,632 deletions on the `data/category-porn` file, which has nothing to do with this PR.
I wonder whether it is a mistake during the contribution, please double-check your commit log.

2022-12-30 17:01 UTC, rootmelo92118 commented on data/category-porn
> +include:category-ir-porn
@IceCodeNew Well. He just only add one line in here.

2022-12-30 17:32 UTC, rootmelo92118 commented
go to #1394

2022-12-30 17:32 UTC, closed without merging

2023-05-07 07:27 UTC, alirezax5 commented
I'm sorry for the problems, I'm trying to add the important domains properly after the changes in #1644 .

I also noticed that some porn domains of Iranian websites have been added to the porn category
There is no need to create a category for Iranian porn sites?

And one point that I saw, because snapp.ir is a super app, it has several other domains and they are divided into categories such as shopping.
Isn't it better to add them all inside a file called snapp?

2023-05-07 08:11 UTC, rootmelo92118 commented
> I'm sorry for the problems, I'm trying to add the important domains properly after the changes in #1644 .
> 
> I also noticed that some porn domains of Iranian websites have been added to the porn category There is no need to create a category for Iranian porn sites?
> 
> And one point that I saw, because snapp.ir is a super app, it has several other domains and they are divided into categories such as shopping. Isn't it better to add them all inside a file called snapp?

I see.