Update snap
v2fly/domain-list-community pull request #1405
Opened 2023-01-04 11:11 UTC by rootmelo92118

2023-01-04 14:50 UTC, IceCodeNew commented on data/snap
> +impala-media-production.s3.amazonaws.com
如果你不打算加 full 前缀或者用注释隔开的话，为什么要单独起一段来放这个域名呢？

2023-01-04 14:52 UTC, rootmelo92118 commented on data/snap
> +impala-media-production.s3.amazonaws.com
我在一分鐘前發現了個問題，並完成修復

2023-01-04 14:54 UTC, IceCodeNew requested changes

2023-01-04 14:54 UTC, IceCodeNew commented on data/snap
>  snapkit.co
看起来这几行前面都有空格，希望能顺手修一下

另外 snapads.com 是不是服务广告目的的域名？

2023-01-04 14:54 UTC, IceCodeNew commented on data/snap
> +full:impala-media-production.s3.amazonaws.com
希望能提供证据

2023-01-04 15:01 UTC, rootmelo92118 commented on data/snap
>  snapkit.co
是，然後我剛排查了一下，並無發現空格。

2023-01-04 15:02 UTC, rootmelo92118 commented on data/snap
> +full:impala-media-production.s3.amazonaws.com
https://github.com/AdguardTeam/HostlistsRegistry/blob/4c596f5d8069e134015a6291b34eb19ea9c65f85/assets/services.json#L1426

2023-01-05 02:11 UTC, IceCodeNew commented on data/snap
>  snapkit.co
> 是，然後我剛排查了一下，並無發現空格。

是我昨天安卓客户端的显示 bug。把广告域名用 `@ads` 标注一下吧。

2023-01-05 06:01 UTC, IceCodeNew approved these changes

2023-01-05 06:02 UTC, merged