Update vimeo
v2fly/domain-list-community pull request #1407
Opened 2023-01-04 14:30 UTC by rootmelo92118

2023-01-04 14:52 UTC, IceCodeNew commented
有域名记录可以分享一下吗？
首先我需要确认这个正则表达式能准确匹配相关的域名（而且不会错误匹配到其他域名）。
另外我希望评估是否值得在这里引入正则表达式。

2023-01-04 14:55 UTC, rootmelo92118 commented
> 有域名记录可以分享一下吗？
> 首先我需要确认这个正则表达式能准确匹配相关的域名（而且不会错误匹配到其他域名）。
> 另外我希望评估是否值得在这里引入正则表达式。

<img width="1136" alt="截圖 2023-01-04 下午10 54 07" src="https://user-images.githubusercontent.com/32770959/210582480-6b6ec3f2-09c6-4797-8a27-8665dfef0045.png">
前面數字的具體位數我也不知道，所以我只能這樣寫。

2023-01-05 02:14 UTC, IceCodeNew commented on data/vimeo
> +regexp:^[0-9]+vod-adaptive\.akamaized\.net$
```suggestion
71vod-adaptive.akamaized.net
```

2023-01-05 02:14 UTC, IceCodeNew requested changes
1. 修改建议已在上面给出
2. 目前提交的证据好像并不能证明这个域名是 vimeo 在用的

2023-01-05 03:26 UTC, rootmelo92118 commented
> 1. 修改建议已在上面给出
> 2. 目前提交的证据好像并不能证明这个域名是 vimeo 在用的

資料來源：
https://github.com/AdguardTeam/HostlistsRegistry/blob/7c0bfc7e085c8192febf5b8445520cc615a94eb9/assets/services.json#L1564

2023-01-05 05:59 UTC, IceCodeNew requested changes

2023-01-05 05:59 UTC, IceCodeNew commented on data/vimeo
> +full:1vod-adaptive.akamaized.net
这个看起来只是邮件标题打错了

2023-01-05 09:11 UTC, IceCodeNew commented on data/vimeo
> +regexp:^[0-9]+vod-adaptive\.akamaized\.net$
是否应该直接匹配所有字符？

2023-01-06 03:05 UTC, rootmelo92118 commented on data/vimeo
> +regexp:^[0-9]+vod-adaptive\.akamaized\.net$
> 是否应该直接匹配所有字符？

目前了解的的情況是前面只有位數無法確定的數字。

2023-01-06 03:13 UTC, IceCodeNew approved these changes

2023-01-06 03:13 UTC, merged