Add aplaybox.com, youngmoe.com
v2fly/domain-list-community pull request #1436
Opened 2023-01-23 08:50 UTC by ShiinaRinne

2023-01-23 10:20 UTC, IceCodeNew requested changes

2023-01-23 10:20 UTC, IceCodeNew commented on data/aplaybox
> +aplaybox.com @cn
需要在文件最后一行加一个空行

2023-01-23 10:20 UTC, IceCodeNew commented on data/youngmoe
> +blog.youngmoe.com
需要在文件最后一行加一个空行

2023-01-23 10:20 UTC, IceCodeNew commented on data/aplaybox
> +# 模之屋
为什么要为了单独一个域名添加新的分类文件？
`data/category-xxx` 中是否有适合的分类？

2023-01-23 10:20 UTC, IceCodeNew commented on data/youngmoe
> +youngmoe.com @cn
> 该网站原维护者被抓跑路了

https://youngmoe.com/

2023-01-23 10:40 UTC, ShiinaRinne commented on data/aplaybox
> +# 模之屋
在分类中归属于 `category-entertainment`, 但是文件最开始的注释中写着 `outside China mainland`, 没有找到`-cn`相关的分类. 
而这个是在国内提供服务的, 翻到几个单独域名作为分类的文件后, 就考虑了也将这个作为新的分类.

2023-01-23 10:46 UTC, ShiinaRinne commented on data/youngmoe
> +youngmoe.com @cn
这是我团队使用的域名, 之前@解析用来提供一些数据展示与查询服务, 后来因为一些事, 部分成员不方便做下去, 就计划停站, 并将主页改成了这个, 这句话算是觉得好玩, 带点调侃的意味. 
短时间内没有规划再提供其他服务, 本次添加主要目的是为了三级域名的直连.

2023-01-23 11:47 UTC, ShiinaRinne commented on data/youngmoe
> +youngmoe.com @cn
![image](https://user-images.githubusercontent.com/45081750/214031876-44c9711e-202d-4abc-a220-e636e45f4f21.png)
补充一个当时的[快照](https://web.archive.org/web/20211116010229/https://youngmoe.com/)

2023-01-23 11:51 UTC, rootmelo92118 commented on data/youngmoe
> +blog.youngmoe.com
youngmoe.com 會匹配 blog.youngmoe.com 不需額外加入

2023-01-23 13:34 UTC, ShiinaRinne commented on data/youngmoe
> +blog.youngmoe.com
blog指向一个国外的服务器, 想将这个通过代理的方式连接, 这个就有些偏向于自己方便了, 不合适我会移除

2023-01-23 13:36 UTC, ShiinaRinne commented on data/aplaybox
> +aplaybox.com @cn
已添加

2023-01-23 13:36 UTC, ShiinaRinne commented on data/youngmoe
> +blog.youngmoe.com
已添加

2023-01-23 13:55 UTC, rootmelo92118 commented on data/youngmoe
> +blog.youngmoe.com
那我個人建議使用full: 語法

2023-01-23 13:58 UTC, ShiinaRinne commented on data/youngmoe
> +blog.youngmoe.com
ok, 感谢!

2023-01-24 13:04 UTC, IceCodeNew requested changes

2023-01-24 13:04 UTC, IceCodeNew commented on data/aplaybox
> +# 模之屋
> 在分类中归属于 `category-entertainment`, 但是文件最开始的注释中写着 `outside China mainland`, 没有找到`-cn`相关的分类. 而这个是在国内提供服务的, 翻到几个单独域名作为分类的文件后, 就考虑了也将这个作为新的分类.

可以直接添加到 `geolocation-cn` 里

2023-01-24 13:04 UTC, IceCodeNew commented on data/youngmoe
> +guanceshu.com @cn
https://dnspod.qcloud.com/static/webblock.html?d=guanceshu.com

2023-01-24 13:04 UTC, IceCodeNew commented on data/youngmoe
> +yae.ac.cn @cn
https://dnspod.qcloud.com/static/webblock.html?d=yae.ac.cn

2023-01-24 13:37 UTC, ShiinaRinne commented on data/youngmoe
> +guanceshu.com @cn
已移除未备案域名

2023-01-24 13:37 UTC, ShiinaRinne commented on data/youngmoe
> +yae.ac.cn @cn
已移除未备案域名

2023-01-24 13:40 UTC, ShiinaRinne commented on data/youngmoe
> +blog.youngmoe.com
已修改完成~

2023-01-27 04:03 UTC, rootmelo92118 approved these changes

2023-01-27 04:05 UTC, rootmelo92118 commented
在geolocation-cn或geolocation-!cn中找一個是的類別並使用include語法將其引入

2023-01-29 07:01 UTC, ShiinaRinne commented
> 在geolocation-cn或geolocation-!cn中找一個合適的類別並使用include語法將其引入 @ShiinaRinne

完成了, 抱歉这两天忙没看, 麻烦了~

2023-01-29 08:33 UTC, rootmelo92118 commented
感謝你的貢獻與配合。

2023-01-29 08:34 UTC, merged

2023-01-30 08:24 UTC, IceCodeNew commented
@rootmelo92118 流程上来说之前提过修改意见的 reviewer，最好在把 requested change 状态改成 approve 以后其他人才能合并 pr
这次刚好春节假期我很长时间没有响应，所以你决定绕过我标记问题解决也是可以理解的

类似的情况之后建议先 at 对方，提醒他处理。如果很长时间没有收到回应（最好把假期也考虑进去），再绕过对方处理

---

回到这个具体的例子。当我收到 @ShiinaRinne 最新的回应以后，我会建议他把 `youngmoe.com @cn` 这条记录删掉。因为他说了这个规则对他来说只是顺带加上的，不加也没有关系
而这个规则和 `full:blog.youngmoe.com @!cn` 放在一块又很令人费解……加大了维护成本。

2023-01-30 10:54 UTC, ShiinaRinne commented
那么需要我之后顺带删掉吗?
我无意让维护成本加大, 也只有极少一部分人能获取方便.
对自己来说配置这个也是很轻松的事, 算不上麻烦, 感觉删掉会更好.

2023-01-30 11:13 UTC, IceCodeNew commented
> 那么需要我之后顺带删掉吗? 我无意让维护成本加大, 也只有极少一部分人能获取方便. 对自己来说配置这个也是很轻松的事, 算不上麻烦, 感觉删掉会更好.

不用特别做这件事~以后顺带做做可以