Update category-enterainment. Remove youngmoe.
v2fly/domain-list-community pull request #1452
Opened 2023-01-31 14:47 UTC by ShiinaRinne

https://github.com/v2fly/domain-list-community/pull/1436#issuecomment-1408434205
删除了之前提交的`youngmoe`, 同时添加了几个新的domain至`category-enterainment`

2023-01-31 14:48 UTC, ShiinaRinne commented
这12个commit....emmm

2023-02-01 01:56 UTC, IceCodeNew commented on data/category-entertainment
> +atwiki.jp
> みんなでアニメや ゲーム情報を共有しよう！

分类到娱乐下感觉不是很准确，也许是我想错了，欢迎进一步讨论。
wiki 类的网站我觉得值得单独开一个分类。

2023-02-01 01:56 UTC, IceCodeNew commented on data/category-entertainment
> +lapriere.jp
偶像团体的官网同样感觉不适合这个分类。

2023-02-01 01:57 UTC, IceCodeNew commented
> remove youngmoe

这个修改没有实现。

2023-02-01 01:57 UTC, IceCodeNew requested changes
> remove youngmoe

这个修改没有实现。

2023-02-01 02:41 UTC, ShiinaRinne commented
> > remove youngmoe
> 
> 这个修改没有实现。

昨天脑抽, 先push上去才去从这个库拉最新的代码, 结果又合回去了...

2023-02-01 03:10 UTC, ShiinaRinne commented on data/youngmoe
> -youngmoe.com @cn
是的, 不需要了
https://github.com/v2fly/domain-list-community/pull/1436#issuecomment-1408434205

2023-02-01 03:31 UTC, ShiinaRinne commented on data/category-entertainment
> +lapriere.jp
巡演, 魔法未来和雪未来主要发布一些最新活动的消息/新闻, `category-media`似乎可以, 其他的就感觉好像哪都不合适
倒是miku站点多, 或许可以单独做个miku分类xd, 再添加一个偶像艺人/虚拟歌手/vtb这样的分类

```
# Media & News & Press
include:category-media
```

2023-02-01 03:43 UTC, IceCodeNew commented on data/category-entertainment
> +atwiki.jp
好的，就放那里吧。

2023-02-01 03:43 UTC, IceCodeNew commented on data/category-entertainment
> +lapriere.jp
> 巡演, 魔法未来和雪未来主要发布一些最新活动的消息/新闻, `category-media`似乎可以, 其他的就感觉好像哪都不合适 倒是miku站点多, 或许可以单独做个miku分类xd, 再添加一个偶像艺人/虚拟歌手/vtb这样的分类
> 
> ```
> # Media & News & Press
> include:category-media
> ```

media 不合适……
我觉得引入一个 ACG 分类都可以

2023-02-01 03:45 UTC, IceCodeNew requested changes
最新状态：
`atwiki.jp` 需要移动到 wiki 分类下

偶像团体及资源分享的网站建议单独建一个 ACG 分类维护。

2023-02-01 04:32 UTC, ShiinaRinne commented
添加了`category-acg`, 放到了`geolocation-!cn`下的`Entertainment`, 这样可以吗?
(可能我个人感觉acg还是属于娱乐下面的)
或者在`geolocation-!cn`里添加一个 `# ACG`?
```
# Entertainment & Games & Music & Podcasts & Videos
include:category-acg
include:category-entertainment
```

2023-02-01 09:38 UTC, IceCodeNew commented
在 `geolocation-!cn` 里添加一个 `# ACG` 吧
@ShiinaRinne

2023-02-01 09:41 UTC, IceCodeNew approved these changes

2023-02-01 09:41 UTC, merged