Update apple, beats, swift and ucloud
v2fly/domain-list-community pull request #1468
Opened 2023-02-10 16:36 UTC by KukiSa

`beatsbydre.com` 苹果电子产品商贸（北京）有限公司 京ICP备10214630号-4
`beatsbydre.com.cn` 苹果电子产品商贸（北京）有限公司 京ICP备10214630号-5

`apple-store.cn`, `applestore.cn`, `applestore.com.cn`, `apple-appstore.cn`, `appleappstore.cn`, `appstoreapple.cn`, `iphone-8.com.cn`, `ipod.com.cn`, `macbookair.cn`, `macbookair.cn`, `applepaycash.cn`, `applepaycash.com.cn`, `applepaysupplies.cn`, `applepaysupplies.com.cn`, `appletv4.cn`, `appletv4.com.cn`, `apple-ibooks.cn`, `apple-maps.cn`, `applecenter.cn`, `applecenter.com.cn`, `applecomputer.cn`, `applecomputer.com.cn`, `applesiri.cn`, `ecgapp.com.cn`, `faceshift.cn`, `homepod.cn`, `insidear.cn`, `livephotos.cn`, `livephotos.com.cn`, `xn--ohq11k7pl25iyo8a.cn`, `swiftui.cn`, `swiftui.com.cn`, `beatsep.cn`, `beats1.cn`, `beats1.com.cn`, `beats2.com.cn`, `beats4.cn` 已不存在备案。

```
# dig www.applestore.cn +short
applestore.cn.
17.253.142.4
```

```
# dig www.applestore.com.cn +short
applestore.com.cn.
17.253.142.4
```

```
# dig www.ipod.com.cn +short
ipod.com.cn.
17.253.142.4
```

```
# dig www.macbookair.com.cn +short
macbookair.com.cn.
17.253.142.4
```

```
# dig www.applecomputer.cn +short
applecomputer.cn.
17.253.142.4
```

```
# dig www.applecomputer.com.cn +short
applecomputer.com.cn.
17.253.142.4
```

`17.253.142.4` 美国 apple.com

其他被削去 `@cn` 标记的条目已经没有有效的 DNS 记录。

---

至于 `ucloud` 那个，我也不知道怎么会多出一条重复的条目来。经查实 `沪ICP备12020087号-19` 没有对应的域名，`ucloudstack.cn` 只对应 `沪ICP备12020087号-14`。

2023-02-10 16:39 UTC, rootmelo92118 commented
我對於使用`cn`作為域名移除`@cn`屬性不持異議，但我希望有第三人能夠裁定。

2023-02-10 16:39 UTC, KukiSa commented
关于 Apple DNS，因为虽然没有备案，但按照相关规定，在中国大陆仅提供 Web 服务的域名需要备案，DNS 服务不受此限；且查证用于 DNS 的域名的普遍解析位置较为困难，故不作 `@cn` 标签削除处理。

2023-02-10 16:57 UTC, KukiSa commented
> 我對於使用`cn`作為域名移除`@cn`屬性不持異議，但我希望有第三人能夠裁定。

抽样调查被削除 `@cn` 标签的域名均未有过备案历史，私以为 Apple 所持有的部分 `.cn` 域名仅用于营销跳转或避免争议，而未有至中国大陆备案以开展相关业务的考虑。本仓库对 Apple 的 `.cn` 域名均标注 `@cn` 标签可能为创建时批量编辑所致而非严谨的做法，因此削去 `@cn` 标签符合情理。

2023-02-12 09:22 UTC, IceCodeNew commented
这个 pr 留着我周一来处理吧。
@KukiSa @rootmelo92118

2023-02-13 08:01 UTC, IceCodeNew commented
不确定我对上面的讨论是否理解正确，这里说下我读过以后的理解，麻烦 @KukiSa 确认下
删掉 `@cn` 是基于两点考量：
1. 这些域名没有有效的备案信息，无法在国内提供服务。你猜测这些域名只是为了占位避免侵权纠纷
2. 这些域名的 www 子域名解析结果看起来归宿地为美国

基于以上理解，我不建议删除 `@cn` 标签。以下是我的理由：
1. `@cn` 标签也被用于以下这种场景：在生成需要代理的域名列表时，排除掉不需要代理的域名。虽然这种用法基本超出了本项目的维护范围，但是特意去删掉这些标签似乎并不能带来什么好处。没有必要特意去破坏其他人已经习惯的用法
2. 全部查 www 子域名的做法不是很合理。IP 解析结果也会和测试方的网络环境有关。推荐通过 https://www.boce.com/ 之类的网站做比较全面的查询。另外通过 IP 地址反查地理信息时也可能会获得错误信息

综上，希望能确认下是否有什么具体的场景因为域名标注了 `@cn` 属性导致了问题。
如果没有造成具体的问题，我觉得这种标注错误继续保留下去反而比较好。

2023-02-13 10:02 UTC, KukiSa commented
> 不确定我对上面的讨论是否理解正确，这里说下我读过以后的理解，麻烦 @KukiSa 确认下 删掉 `@cn` 是基于两点考量：
> 
> 1. 这些域名没有有效的备案信息，无法在国内提供服务。你猜测这些域名只是为了占位避免侵权纠纷
> 2. 这些域名的 www 子域名解析结果看起来归宿地为美国
> 
> 基于以上理解，我不建议删除 `@cn` 标签。以下是我的理由：
> 
> 1. `@cn` 标签也被用于以下这种场景：在生成需要代理的域名列表时，排除掉不需要代理的域名。虽然这种用法基本超出了本项目的维护范围，但是特意去删掉这些标签似乎并不能带来什么好处。没有必要特意去破坏其他人已经习惯的用法
> 2. 全部查 www 子域名的做法不是很合理。IP 解析结果也会和测试方的网络环境有关。推荐通过 https://www.boce.com/ 之类的网站做比较全面的查询。另外通过 IP 地址反查地理信息时也可能会获得错误信息
> 
> 综上，希望能确认下是否有什么具体的场景因为域名标注了 `@cn` 属性导致了问题。 如果没有造成具体的问题，我觉得这种标注错误继续保留下去反而比较好。

目前没有因 `@cn` 标签造成的明显的问题。

对于 IP 地址归属的问题在提交前我会对其进行基于 ipip.net 和三家 ISP 的路由查询，由于国内的政策并不允许随意将 IP 地址段广播在国内，因此我对于 IP 地址的判断并不会有问题。
Apple 几乎所有的服务（除 DNS 外）均基于已备案的数个域名及其子域名，热衷取得各个市场合规性的 Apple 并不会违规进行 DNS 解析和服务。

不过本 PR 涉及到的大部分域名均不重要，出于传统和稳定性而维持现状的决定也是能够接受的。本 PR 可最终仅保留对 `ucloud` 的更改而合并。

2023-02-13 11:09 UTC, IceCodeNew requested changes
> 不过本 PR 涉及到的大部分域名均不重要，出于传统和稳定性而维持现状的决定也是能够接受的。本 PR 可最终仅保留对 ucloud 的更改而合并。

那就这么做吧。

2023-02-17 00:36 UTC, rootmelo92118 commented
> hi!可以再测试一下apple-Podcasts的域名吗！ #Podcasts
> 
> ```
> bag.itunes.apple.com
> amp-api.podcast.apple.com
> bookeeper.itunes.apple.com
> buzzsprout.com
> ```
> 
> 下面几个是我找到的，但是目前还是进不去Podcasts搜索 美版ID，日版vps

請自行提交拉取請求，我們會單獨審核。

2023-02-19 13:46 UTC, rootmelo92118 approved these changes

2023-02-19 13:48 UTC, rootmelo92118 commented
@IceCodeNew 已修改為取得共識之內容，沒有問題的話即可合併。

2023-02-20 03:24 UTC, IceCodeNew approved these changes

2023-02-20 03:24 UTC, IceCodeNew commented on data/apple
> +xn--fiqs8sxootzz.cn @cn # 苹果中国.cn
实践上似乎一般 `.cn` 域名都不加 `@cn` 属性，我觉得也没有特别的道理。总之我觉得这里加上也没问题。

2023-02-20 03:24 UTC, merged