Add 'ugdtimg.com' to 'tencent'
v2fly/domain-list-community pull request #1477
Opened 2023-02-15 17:42 UTC by zedifen

Add 'ugdtimg.com' to 'tencent'. However, I'm not sure if this is an ad domain or not.

2023-02-16 01:09 UTC, rootmelo92118 commented
Where did you get it?

2023-02-16 02:20 UTC, IceCodeNew requested changes
more info is needed

2023-02-16 10:59 UTC, yin1999 commented
see https://icp.chinaz.com/ugdtimg.com

2023-02-17 00:32 UTC, rootmelo92118 approved these changes

2023-02-17 00:49 UTC, zedifen commented
So sad I can't remember where I encountered this domain. But as the comment above said, it's ineed a Tencent one.

2023-02-17 03:16 UTC, IceCodeNew requested changes
<img width="518" alt="image" src="https://user-images.githubusercontent.com/32576256/219540529-303989d1-2ec4-4dd2-b0f2-268c38228dcb.png">

这个域名，麻烦找下其他材料确认下是否是广告用途吧。是的话把 `@ads` 标签加上
从目前看到的信息来说，这个域名没有立刻合并的必要。所以虽然能确认是腾讯的域名，但除非知道具体什么场景下需要用到它，或者能够解决上面的疑问，否则我觉得没必要推合并

2023-02-24 01:46 UTC, rootmelo92118 commented
https://github.com/neoFelhz/neohosts/issues/47

@IceCodeNew 目前研判其作為廣告用途。

2023-02-24 02:04 UTC, IceCodeNew commented
> [neoFelhz/neohosts#47](https://github.com/neoFelhz/neohosts/issues/47)
> 
> @IceCodeNew 目前研判其作為廣告用途。

收到，麻烦你帮忙改一下吧。

2023-02-24 02:30 UTC, closed without merging