add olevod to category-entertainment
v2fly/domain-list-community pull request #1502
Opened 2023-02-24 14:20 UTC by dijingkai

2023-02-24 15:58 UTC, rootmelo92118 requested changes
Please sort the content after your modification and leave a new line after the last domain.

2023-02-25 01:13 UTC, rootmelo92118 commented
What did you upload? `oryxBuildBinary`?

2023-02-25 01:20 UTC, dijingkai commented
> What did you upload? `oryxBuildBinary`?

I don't know, maybe it was an autogenerated file, I've deleted it now

2023-02-25 01:20 UTC, rootmelo92118 approved these changes

2023-02-25 01:20 UTC, merged