Update tld-!cn
v2fly/domain-list-community pull request #1557
Opened 2023-03-25 13:07 UTC by rootmelo92118

2023-03-27 06:25 UTC, IceCodeNew commented
Just give me more time on this.

2023-03-31 15:34 UTC, IceCodeNew commented
The newest ETA is the coming Saturday night, thanks for everyone being patient.

2023-04-01 16:22 UTC, IceCodeNew requested changes

2023-04-01 16:22 UTC, IceCodeNew commented on data/tld-!cn
> -an # Antilles (Netherlands)
请解释下为什么要删掉这行

2023-04-01 16:22 UTC, IceCodeNew commented on data/tld-!cn
> +ax # Åland
这里的 rename 也需要解释

2023-04-01 16:22 UTC, IceCodeNew commented on data/tld-!cn
> -gb # United Kingdom
为什么要删掉这行？

2023-04-01 16:22 UTC, IceCodeNew commented on data/tld-!cn
> -su # Soviet Union
这个域名也不能使用了吗？

2023-04-01 16:22 UTC, IceCodeNew commented on data/tld-!cn
> -tp # Portuguese Timor
需要补充说明

2023-04-01 16:22 UTC, IceCodeNew commented on data/tld-!cn
> -um # United States Minor Outlying Islands
需要补充说明

2023-04-03 04:49 UTC, rootmelo92118 commented on data/tld-!cn
> -an # Antilles (Netherlands)
https://en.wikipedia.org/wiki/.an

該頂級域已被移除。

2023-04-03 04:49 UTC, rootmelo92118 commented on data/tld-!cn
> -tp # Portuguese Timor
https://en.wikipedia.org/wiki/.tp

該頂級域已被移除。

2023-04-03 04:49 UTC, rootmelo92118 commented on data/tld-!cn
> -um # United States Minor Outlying Islands
https://en.wikipedia.org/wiki/.um

該頂級域已被移除

2023-04-03 04:49 UTC, rootmelo92118 commented on data/tld-!cn
> -gb # United Kingdom
雖然已經沒有域名向這個頂級域解析，不過尚未正式被ICANN移除，先保留好了。

2023-04-03 04:50 UTC, rootmelo92118 commented on data/tld-!cn
> +ax # Åland
已恢復

2023-04-03 04:50 UTC, rootmelo92118 commented on data/tld-!cn
> -su # Soviet Union
已恢復

2023-04-04 09:03 UTC, IceCodeNew approved these changes

2023-04-04 09:37 UTC, IceCodeNew commented
Do not merge before I give the final clearance

2023-04-04 10:01 UTC, rootmelo92118 commented on data/tld-!cn
> +nl # Sint Eustatius
複製粘貼忘了

2023-04-04 10:41 UTC, IceCodeNew requested changes

2023-04-04 10:41 UTC, IceCodeNew commented on data/tld-!cn
> +nl # Sint Eustatius
改好了和我说一声吧。我明天不一定会看 GitHub @rootmelo92118

2023-04-04 11:31 UTC, rootmelo92118 commented on data/tld-!cn
> +nl # Sint Eustatius
> 改好了和我说一声吧。我明天不一定会看 GitHub @rootmelo92118

@IceCodeNew done

2023-04-05 09:02 UTC, IceCodeNew approved these changes

2023-04-05 09:03 UTC, merged