Solve multiple parent node problem and decrease it (geolocation-!cn)
v2fly/domain-list-community pull request #1567
Opened 2023-03-26 09:57 UTC by rootmelo92118

#1561

2023-04-01 16:55 UTC, IceCodeNew requested changes

2023-04-01 16:55 UTC, IceCodeNew commented on data/geolocation-!cn
> +chemequations.com
给这个域名加一行注释，写上分类吧。

2023-04-03 04:29 UTC, rootmelo92118 commented on data/geolocation-!cn
> +chemequations.com
done

2023-04-04 09:05 UTC, IceCodeNew approved these changes

2023-04-04 09:06 UTC, merged