Solve multiple parent node problem and decrease it (category-companies)
v2fly/domain-list-community pull request #1571
Opened 2023-03-26 10:14 UTC by rootmelo92118

#1561

2023-04-01 16:54 UTC, IceCodeNew requested changes

2023-04-01 16:54 UTC, IceCodeNew commented on data/hubblephone
> -hubblephone.com
为什么删除这个分类？

2023-04-03 04:27 UTC, rootmelo92118 commented on data/hubblephone
> -hubblephone.com
該域名已被重定向至新網站，所以我在引入類別中加入重定向後的一條域名並將原分類移除

2023-04-04 11:36 UTC, rootmelo92118 commented on data/hubblephone
> -hubblephone.com
done

2023-04-05 09:01 UTC, merged