openai cdn
v2fly/domain-list-community pull request #1587
Opened 2023-04-01 14:33 UTC by yubanmeiqin9048

2023-04-01 16:10 UTC, IceCodeNew requested changes

2023-04-01 16:10 UTC, IceCodeNew commented on data/openai
> +full:openaicom-api-bdcpf8c6d2e9atf6.z01.azurefd.net
方便提供下这个域名是 CDN 域名的证据吗？

2023-04-02 02:01 UTC, EpLiar commented
![image](https://user-images.githubusercontent.com/23559565/229327020-876d6367-659f-4a77-a931-54f570d8a9c6.png)

2023-04-02 02:01 UTC, EpLiar approved these changes

2023-04-02 02:02 UTC, merged

2023-04-02 03:29 UTC, IceCodeNew commented
> ![image](https://user-images.githubusercontent.com/23559565/229327020-876d6367-659f-4a77-a931-54f570d8a9c6.png)

@EpLiar 
不是啊，如果这个域名不是 CDN 用途而是用户跟踪，或者其他用途呢？我希望确认的是这一点
我希望以后如果有 reviewer 提出疑问了，等到 reviewer 亲自确认以后再合并（除非对方很长时间没有回复，提醒他也无用
这个 PR 合太急了

2023-04-02 03:35 UTC, IceCodeNew commented
BTW 合并 PR 时请 squash & rebase

2023-04-02 03:36 UTC, EpLiar commented
这个域名的连接响应我看了一下，大概是一些 meta 信息，如果确实不符合 cdn 就 revert 吧