Add neshanmap.ir, tapsell.ir, yektanet.com
v2fly/domain-list-community pull request #1596
Opened 2023-04-03 15:22 UTC by keikhosrow

2023-04-04 09:36 UTC, IceCodeNew requested changes

2023-04-04 09:36 UTC, IceCodeNew commented on data/category-ir-tech
> +tapsell.ir
if this domain belongs to an e-commerce site, we should move it to a category named `category-ir-e-commerce` or something.

2023-04-16 08:11 UTC, rootmelo92118 commented on data/category-ir-tech
> +yektanet.com
<img width="1440" alt="截圖 2023-04-16 下午4 11 00" src="https://user-images.githubusercontent.com/32770959/232284073-850d378a-532b-449d-bde4-98566e1b66f0.png">
This website is about advertising.

2023-04-16 08:12 UTC, rootmelo92118 commented on data/category-ir-tech
> +tapsell.ir
<img width="1440" alt="截圖 2023-04-16 下午4 12 38" src="https://user-images.githubusercontent.com/32770959/232284153-a18fa7ce-c14d-42f5-a964-e3cadd605fb5.png">
This website is also about advertising.

2023-04-18 03:29 UTC, IceCodeNew commented
There are 3 actions we can take, which one would you prefer?
1. do not include `tapsell.ir` & `yektanet.com`
2. move these two domains into a category like `category-ir-ads`, which I consider the worst move. Blocking ads/trackers based on domains is not only inaccurate, but also a nightmare for reviewing and maintaining, and a fuse for the copyleft problems
3. keep these domains as they could be considered as _tech companies_

2023-04-19 04:21 UTC, rootmelo92118 commented
> There are 3 actions we can take, which one would you prefer?
> 
> 1. do not include `tapsell.ir` & `yektanet.com`
> 2. move these two domains into a category like `category-ir-ads`, which I consider the worst move. Blocking ads/trackers based on domains is not only inaccurate, but also a nightmare for reviewing and maintaining, and a fuse for the copyleft problems
> 3. keep these domains as they could be considered as _tech companies_
> 
> @rootmelo92118

@IceCodeNew I am prefer the third action. Do you have any opinion?

2023-04-19 06:02 UTC, keikhosrow commented
Hello, due to the fact that the biggest advertising platform in Iran are four websites: Yektanet, Tapsel, Saba Vision and Tavus, I think the third option is better for now.

2023-04-19 07:20 UTC, rootmelo92118 approved these changes

2023-04-19 10:24 UTC, IceCodeNew commented
> Hello, due to the fact that the biggest advertising platform in Iran are four websites: Yektanet, Tapsel, Saba Vision and Tavus, I think the third option is better for now.

I am OK with that. Thanks for feeding back.

2023-04-19 10:24 UTC, IceCodeNew approved these changes

2023-04-19 10:25 UTC, merged