Create category-blog-cn
v2fly/domain-list-community pull request #1659
Opened 2023-05-12 13:41 UTC by Nep-Timeline

2023-05-13 15:05 UTC, IceCodeNew approved these changes

2023-05-13 15:05 UTC, IceCodeNew commented
LGTM.
@rootmelo92118 what do you think?

2023-05-13 15:06 UTC, IceCodeNew commented
suppressed #1658

2023-05-15 01:35 UTC, IceCodeNew requested changes

2023-05-15 01:35 UTC, IceCodeNew commented on data/category-blog-cn
> +owo.today
<img width="623" alt="image" src="https://github.com/v2fly/domain-list-community/assets/32576256/09e16b96-480d-4fdd-af63-5cdc3a3b51c0">

please provide an accessible URL for verification.

2023-05-15 03:28 UTC, Nep-Timeline commented on data/category-blog-cn
> +owo.today
me.owo.today

2023-05-15 06:56 UTC, IceCodeNew commented on data/category-blog-cn
> +owo.today
> me.owo.today

这个域名的解析结果指向阿里云香港。和 `category-blog-cn` 分类原则不符。

2023-05-15 06:58 UTC, IceCodeNew commented on data/category-blog-cn
> +owo.today
不要擅自把讨论内容标记成已解决。这样很容易漏掉一些还没讨论清楚的问题

2023-05-15 06:58 UTC, rootmelo92118 commented
> LGTM.
> @rootmelo92118 what do you think?

I think it looks ok.

2023-05-15 07:03 UTC, Nep-Timeline commented on data/category-blog-cn
> +owo.today
> 不要擅自把讨论内容标记成已解决。这样很容易漏掉一些还没讨论清楚的问题

好的

2023-05-15 07:06 UTC, IceCodeNew commented
> > LGTM.
> > @rootmelo92118 what do you think?
> 
> I think it looks ok.

The last commit should be reverted before we merge this PR.

2023-05-15 07:07 UTC, IceCodeNew approved these changes

2023-05-15 07:07 UTC, merged