Create anthropic
v2fly/domain-list-community pull request #1662
Opened 2023-05-13 17:05 UTC by FDUZS

close #1660

2023-05-14 09:04 UTC, IceCodeNew requested changes

2023-05-14 09:04 UTC, IceCodeNew commented on data/anthropic
> +www.anthropic.com
```suggestion
```

2023-05-14 09:04 UTC, IceCodeNew commented on data/anthropic
> +slackbot.anthropic.com
```suggestion
```

2023-05-14 09:04 UTC, IceCodeNew commented on data/anthropic
> +# Main domain
```suggestion
```

2023-05-15 02:12 UTC, EpLiar approved these changes

2023-05-15 03:03 UTC, IceCodeNew approved these changes

2023-05-15 03:04 UTC, merged