Update category-porn
v2fly/domain-list-community pull request #1679
Opened 2023-05-25 07:03 UTC by bijoni

2023-05-28 06:15 UTC, rootmelo92118 approved these changes

2023-05-29 02:53 UTC, IceCodeNew requested changes

2023-05-29 02:53 UTC, IceCodeNew commented on data/category-porn
> +regexp:(^|\.)whtdh0[1-3]\.cc$
sort

2023-05-29 02:53 UTC, IceCodeNew commented on data/category-porn
> +regexp:(^|\.)tttv[1-100]\.com$
It does not look right to me

2023-05-29 02:53 UTC, IceCodeNew commented
@rootmelo92118 要检查得仔细一点哦。

2023-05-29 10:25 UTC, bijoni commented on data/category-porn
> +regexp:(^|\.)whtdh0[1-3]\.cc$
Sorted

2023-05-29 10:27 UTC, bijoni reviewed
Amended the sorting

2023-05-29 10:35 UTC, bijoni commented on data/category-porn
> +regexp:(^|\.)tttv[1-100]\.com$
Verified with no problem.

2023-05-29 10:38 UTC, rootmelo92118 commented on data/category-porn
> +regexp:(^|\.)tttv[1-100]\.com$
> Verified with no problem.

Could you provide the original domains?

2023-05-29 10:42 UTC, bijoni commented on data/category-porn
> +regexp:(^|\.)tttv[1-100]\.com$
From tttv1.com through tttv100.com

2023-05-29 10:45 UTC, rootmelo92118 commented on data/category-porn
> +regexp:(^|\.)tttv[1-100]\.com$
> From tttv1.com through tttv100.com

Do you know it will only match tttv1.com and tttv0.com ?

2023-05-29 10:50 UTC, rootmelo92118 commented on data/category-porn
> +regexp:(^|\.)tttv[1-100]\.com$
According to rule `tttv+1-100任意数.com` on the home page in [tttv1.com](tttv1.com), I rewrote a new pattern
```
(^|\.)tttv([1-9]|[1-9][0-9]|100)\.com$
```
What do you think? @IceCodeNew @bijoni

2023-05-29 10:54 UTC, rootmelo92118 commented on data/category-porn
> +regexp:(^|\.)tttv[1-100]\.com$
@IceCodeNew Solved.

2023-05-29 11:45 UTC, IceCodeNew commented on data/category-porn
> +regexp:(^|\.)tttv[1-100]\.com$
`[1-100]` does not make sense.

2023-05-29 11:52 UTC, IceCodeNew approved these changes

2023-05-29 11:52 UTC, merged