Create trackers
v2fly/domain-list-community pull request #1686
Opened 2023-05-28 20:38 UTC by mmrabbani

This list contains top web trackers. blocking this list can help privacy oriented users.

2023-05-28 20:42 UTC, mmrabbani commented
this list can be add to "category-ads-all". But I didn't add this. because I think maintainers may not like this

2023-05-29 02:50 UTC, IceCodeNew requested changes

2023-05-29 02:50 UTC, IceCodeNew commented on data/trackers
> +appcenter.ms
this will match domains that are not for tracking users.

2023-05-29 02:50 UTC, IceCodeNew commented on data/trackers
> +app-measurement.com
already exist.

2023-05-29 02:50 UTC, IceCodeNew commented on data/trackers
> +crashlytics.com
already exist.

2023-05-29 02:50 UTC, IceCodeNew commented on data/trackers
> +google-analytics.com
already exist.

2023-05-29 03:03 UTC, closed without merging