Update falungong
v2fly/domain-list-community pull request #1724
Opened 2023-06-20 13:25 UTC by FDUZS

2023-06-20 14:53 UTC, rootmelo92118 commented
你所添加的域名皆已存在於本專案中
<img width="804" alt="截圖 2023-06-20 下午10 52 00" src="https://github.com/v2fly/domain-list-community/assets/32770959/3e3d9dc2-1420-440f-bba5-1be4af6b5240">

2023-06-20 14:54 UTC, rootmelo92118 requested changes
您所添加的域名皆已存在於本專案中
<img width="804" alt="截圖 2023-06-20 下午10 52 00" src="https://github.com/v2fly/domain-list-community/assets/32770959/fc5eb528-4c25-440c-a74f-e64ddd75cc2b">

2023-06-21 01:44 UTC, IceCodeNew commented
> 皆已存在於本專案中

那这个 pr 直接关了吧。辛苦你和 @FDUZS 继续解释一下脚本执行的结果代表什么意思。

2023-06-21 09:15 UTC, rootmelo92118 commented
> I DO NOT know what you mean

I think that you can understand Chinese because you used Chinese to submit issue #1723. According to your home page on GitHub, your location is in Beijing and it has a lot of Chinese content in your repository. Although I don't believe you can not understand what I mean, the message I leave means "The domain names that you submitted already exists in this project".

v2ray允許依據geosite中的類別在dns中返回特定解析結果。
所以我們可以依此來使其返回特定結果來判斷該域名是否存在於該類別中。
你所看到的是依據這個特性所撰寫的腳本來快速辨識域名是否存在於指定類別中。

2023-06-21 13:11 UTC, Loyalsoldier commented
@rootmelo92118 

> v2ray允許依據geosite中的類別在dns中返回特定解析結果。
> 所以我們可以依此來使其返回特定結果來判斷該域名是否存在於該類別中。

这个方式没问题，但是你的检测结果不对啊。

2023-06-21 13:13 UTC, rootmelo92118 commented
> @rootmelo92118
> 
> > v2ray允許依據geosite中的類別在dns中返回特定解析結果。
> > 所以我們可以依此來使其返回特定結果來判斷該域名是否存在於該類別中。
> 
> 这个方式没问题，但是你的检测结果不对啊。

哪裡有問題？

2023-06-21 13:20 UTC, Loyalsoldier commented
> 哪裡有問題？ P.S. 我這次選取的範圍為 `geolocation-!cn`

这些域名都不在本项目里啊。你在编辑器或 GitHub 的搜索功能里搜一下就知道了。

2023-06-21 14:02 UTC, rootmelo92118 commented
<img width="1440" alt="截圖 2023-06-21 下午10 00 33" src="https://github.com/v2fly/domain-list-community/assets/32770959/8546f3c3-6162-45ac-a2c3-8b227db1d260">
好吧，我必須說發生了一個很奇怪的事情，當我封鎖整個`geolocation-!cn`的列表時，所有他提交的域名皆無法正常連線，但我們又無法在專案中找出這個域名的已存在位置。。。

2023-06-21 14:13 UTC, rootmelo92118 approved these changes
@Loyalsoldier 我知道問題在哪裡了，這些域名存在於 https://github.com/Loyalsoldier/v2ray-rules-dat 中引用的gfwlist中，並且引入了geolocation-!cn中，所以對於該專案的使用者會產生“他們”有但官方倉庫沒有的情況，這個PR我會馬上合併。

2023-06-21 14:14 UTC, merged

2023-06-21 14:14 UTC, FDUZS commented
> > 哪裡有問題？ P.S. 我這次選取的範圍為 `geolocation-!cn`
> 
> 这些域名都不在本项目里啊。你在编辑器或 GitHub 的搜索功能里搜一下就知道了。

这就是我说的“I DO NOT know what you mean”

2023-06-21 14:19 UTC, rootmelo92118 commented
> > > 哪裡有問題？ P.S. 我這次選取的範圍為 `geolocation-!cn`
> > 
> > 
> > 这些域名都不在本项目里啊。你在编辑器或 GitHub 的搜索功能里搜一下就知道了。
> 
> 这就是我说的“I DO NOT know what you mean”

了解了，抱歉一開始是誤認以為你說你無法理解中文。