add new crypto sites
v2fly/domain-list-community pull request #1814
Opened 2023-08-30 07:00 UTC by allensakari

add popular crypto sites into catagory.

2023-09-02 04:04 UTC, rootmelo92118 approved these changes

2023-09-02 04:04 UTC, rootmelo92118 commented on data/binance
> +appsflayer.com
Could you provide any evidence to prove this domain is belonging to `binance`?

2023-09-02 04:04 UTC, rootmelo92118 commented on data/category-cryptocurrency
> +mexcsensors.com
Could you provide any evidence to prove this domain is belonging to this category?

2023-09-02 04:04 UTC, rootmelo92118 requested changes

2023-09-02 04:04 UTC, rootmelo92118 commented on data/binance
> +appsflayer.com
Could you provide any evidence to prove this domain is belonging to `binance`?

2023-09-02 04:04 UTC, rootmelo92118 commented on data/category-cryptocurrency
> +mexcsensors.com
Could you provide any evidence to prove this domain is belonging to this category?

2023-09-05 08:13 UTC, rootmelo92118 commented
@allensakari

2023-09-05 13:52 UTC, allensakari commented
> @allensakari

sorry, here are some reference screenshots.
![mexc](https://github.com/v2fly/domain-list-community/assets/113282575/c909d4cd-f4d5-44cb-8a48-0bf629f516d6)
![saasex com](https://github.com/v2fly/domain-list-community/assets/113282575/273f0a36-8a9c-4922-8517-5c1ad4465f4c)

2023-09-11 13:29 UTC, rootmelo92118 approved these changes

2023-09-11 13:29 UTC, merged