Update media
v2fly/domain-list-community pull request #182
Opened 2020-08-26 13:00 UTC by Robot-DaneelOlivaw

Add domains of Bloomberg and Solidot.

2020-08-26 15:44 UTC, EpLiar commented
`data/bbc` 那个可以顺手排序下

2020-08-26 15:54 UTC, EpLiar commented
还有 `category-media`

2020-08-26 16:00 UTC, KevinZonda requested changes

2020-08-26 17:39 UTC, KevinZonda approved these changes

2020-08-27 00:36 UTC, EpLiar commented
insider 那边漏了个 .my 的域名

2020-08-27 00:42 UTC, EpLiar commented
guardian 加个 theguardiandns.com

2020-08-27 00:46 UTC, EpLiar commented
`usatoday` 那边要加的：

- usatodaynetworkservice.com

2020-08-27 00:49 UTC, EpLiar commented
看起来 gannett-cdn.com 和 usatoday 没有关联？可以提供下来源么

2020-08-27 00:53 UTC, EpLiar commented
`sky` 这边：

- skygroup.sky
- skyoceanrescue.de
- skyoceanrescue.it
- skyoceanrescue.com
- skysportsonline.com
- skysports.fr
- skysports.ie
- skysportsracing.com

2020-08-27 01:09 UTC, EpLiar commented
`bloomberg`:

![image](https://user-images.githubusercontent.com/23559565/91371998-0e635600-e845-11ea-8aaf-f721e959e711.png)

2020-08-27 01:19 UTC, EpLiar commented
`newscorp` 那边我不太确定这个：newscgp.com

2020-08-27 04:11 UTC, EpLiar commented
> 具体是哪一个域名？

它们官网不是有一个选地区的嘛，马来西亚那个你漏加了

> USAToday是Gannett的子品牌，会使用到Gannett的CDN。考虑后还是将列表名称更改为`gannett`。

OK

> 如果已经包含了所有.sky域名，还需要添加这一项吗？

这个我的锅，写多了

> 经查验是属于另一家企业的追踪器，已移除，并将`dowjones`合并入`newscorp`。

OK

> 另外Bloomberg的域名是使用amass枚举得到的吗？

ssl 证书会有同一证书下的其他域名。amass 只能求子域

2020-08-27 06:48 UTC, EpLiar requested changes
category-media 那里改名之后排序下，别的应该没啥问题了

2020-08-27 07:31 UTC, EpLiar approved these changes

2020-08-27 07:31 UTC, merged

2020-08-27 07:52 UTC, EpLiar commented
> 感谢纠正，这个PR漏洞百出。

粒度小一点就不容易出错了，也可以减轻 review 负担 (滑水混 GitHub 警告