Rename osu to peppy
v2fly/domain-list-community pull request #1891
Opened 2023-10-30 08:11 UTC by Nep-Timeline

2023-10-30 08:16 UTC, rootmelo92118 approved these changes

2023-10-30 08:17 UTC, rootmelo92118 requested changes
Why?

2023-10-30 08:20 UTC, Nep-Timeline commented
> Why?

https://blog.ppy.sh/
This link belongs to the blog and does not belong to the game 'osu'

2023-10-30 08:23 UTC, rootmelo92118 commented
So... is peppy a company?

2023-10-30 08:29 UTC, rootmelo92118 commented on data/osu
If it does not have any subdomain name, you should use full prefix.

2023-10-30 08:32 UTC, Nep-Timeline commented on data/osu
done

2023-10-30 08:33 UTC, rootmelo92118 approved these changes

2023-10-30 08:35 UTC, rootmelo92118 commented
Now you just need the last step.
Find a relevant category to include `peppy`.

2023-10-30 08:40 UTC, rootmelo92118 requested changes

2023-10-30 08:40 UTC, rootmelo92118 commented on data/category-orgs
> +include:peppy
sort it.

2023-10-30 08:46 UTC, Nep-Timeline commented on data/category-orgs
> +include:peppy
ok

2023-11-05 03:15 UTC, rootmelo92118 approved these changes

2023-11-05 03:15 UTC, merged