Create `category-ntp`
v2fly/domain-list-community pull request #1980
Opened 2023-12-24 21:31 UTC by demarcush

Including all NTP servers I could find.

2023-12-30 16:10 UTC, rootmelo92118 commented
Please include this category to relevant category.

2023-12-30 16:13 UTC, rootmelo92118 requested changes
Please include this category to relevant category.

2024-01-07 15:00 UTC, Hyy2001X commented on data/category-ntp-cn
#Aliyun
full:ntp.aliyun.com
regexp:^ntp([1-7])?.aliyun.com$

#Tencent
full:ntp.tencent.com
regexp:^ntp([1-5])?.tencent.com$

cn.pool.ntp.org
ntp.org.cn

2024-01-23 11:10 UTC, rootmelo92118 approved these changes

2024-01-23 11:10 UTC, merged