update category-ads-all
v2fly/domain-list-community pull request #205
Opened 2020-09-11 16:48 UTC by ajiou

2020-09-11 16:50 UTC, EpLiar commented
你可能需要去看一下本仓库收集域名的格式，而不是统一使用 domain: 前缀

2020-09-11 17:15 UTC, IceCodeNew requested changes

2020-09-11 17:15 UTC, IceCodeNew commented on data/category-ads-all
> +include:category-ads
BTW 不要删掉文件最末尾的空行。

2020-09-12 04:45 UTC, ajiou commented
vortex.data.microsoft.com 被Adguard DNS 内建清单拦截
![2020-09-12_123709](https://user-images.githubusercontent.com/35028055/92987501-9019db80-f4f5-11ea-8e4a-21a52a5fae93.png)

2020-09-12 04:46 UTC, EpLiar requested changes
排序的问题依旧存在

请确保只有一个 commit

2020-09-12 05:28 UTC, IceCodeNew requested changes

2020-09-12 05:28 UTC, IceCodeNew commented on data/google-ads
> +keyword:adservice.google @ads
这个变化有根据吗？你是否观察到了有别的根域名也在屏蔽列表里？
另外即使是存在 `adservice.google.com.hk` 或者 `adservice.google.cat` 这样的域名，使用 regex 匹配也比使用 keyword 匹配好。

2020-09-12 05:33 UTC, IceCodeNew requested changes

2020-09-12 05:33 UTC, IceCodeNew commented on data/category-ads-all
> +vortex.data.microsoft.com @ads
另外这里的标记也不恰当，你不能简单地根据一个域名被 Adguard DNS 内建清单拦截就判断它是广告域名。
实际上这个是微软遥测用的域名，Adguard DNS 内建清单拦截它是为了增强隐私保护。
所以你这里给它加注 ads 属性是非常不恰当的。

Refer: https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/proxifier/spy/domains.txt

2020-09-12 16:07 UTC, EpLiar commented
> * 维护广告域名列表需要庞大社区支持，许多第三方列表与本项目的MIT协议不兼容。

疯狂暗示 dlc 缺人

2020-09-12 16:09 UTC, EpLiar commented
google-ads 的那个regexp 前后是否应该写死一下，避免匹配其他域

2020-09-12 17:54 UTC, ajiou commented
google-ads 的那个regexp 已经指定了是google的，应该很难误匹配

2020-09-13 00:47 UTC, EpLiar commented
> google-ads 的那个regexp 已经指定了是google的，应该很难误匹配

adservice 前面加几个字母也能被匹配

2020-09-13 02:20 UTC, IceCodeNew commented on data/google-ads
> +regexp:^adservice\.google\.com\S{0,4}$ @ads
不理解最后面这个 `\S{0,4}` 是为了匹配什么场景，能说明一下吗？

2020-09-13 03:54 UTC, ajiou commented on data/google-ads
> +regexp:^adservice\.google\.com\S{0,4}$ @ads
.hk
.cat
之类的

2020-09-13 05:06 UTC, IceCodeNew commented on data/google-ads
> +regexp:^adservice\.google\.com\S{0,4}$ @ads
那 `($|\.hk$|\.cat$)` 不是更好，不要写的太宽裕，免得遇到没有料到的问题。
而且如果你确定有这样的情况的话可以加上去，只看到有 `.com` 的情况的话不用提前先把其他的域名写上去，说不定根本用不上。

2020-09-13 08:35 UTC, ajiou commented on data/google-ads
> +regexp:^adservice\.google\.com\S{0,4}$ @ads
我当初就是因为有其他国家的才把他独立出来

2020-09-13 08:45 UTC, IceCodeNew commented on data/google-ads
> +regexp:^adservice\.google\.com\S{0,4}$ @ads
好的，那你有具体的一个列表吗？
没有的话，你是否观察到了特殊字符域名，以至于需要用 `\S{0.4}` 来匹配 punycode 编码的顶级域？

2020-09-13 08:54 UTC, IceCodeNew requested changes

2020-09-13 08:54 UTC, IceCodeNew commented on data/google-ads
> +regexp:^adservice\.google\.com(\...)?$ @ads
我觉得这个匹配思路也不错，改成下面这样，我觉得就可以 merge 这个 PR 了。
`regexp:^adservice\.google\.com(\.[a-z]{2})?$ @ads`

当然我还是比较好奇对你来说到底有哪些域名需要匹配，你知道如果有个列表来交流的话，沟通会更顺利。
比如现在我就好奇 https://github.com/v2fly/domain-list-community/blob/6b8e8be95b87f144447eee11f1b9f77eb1fdc1bd/data/google#L54-L243 这里出现的所有可能的顶级域你是否都觉得有必要匹配上。

2020-09-13 09:08 UTC, ajiou commented on data/google-ads
> +regexp:^adservice\.google\.com(\...)?$ @ads
如果改成这样呢
[](https://regex101.com/r/bDJq7t/1)

2020-09-13 10:45 UTC, IceCodeNew approved these changes

2020-09-13 10:45 UTC, merged

2020-09-13 10:49 UTC, IceCodeNew commented
在 `adservice\.google\.com` 这个域名上我们讨论的太久了。所以我既然已经看到一个足够精细，几乎不会有导致意想不到的问题的正则表达式，那就还是早早结束询问了。
但是对之后的 PR 我的建议是，仅对你看到的域名做广告标记。有缺漏之后再补上都是可以的，不用强求一次性就做到最全最完美。
因为这个 PR 最后说到底是要给别人审核的，而一些在野外没有使用到，几乎没办法查实的域名会大大耽误其他人审核的精力。
@ajiou