add ksord.com into wps
v2fly/domain-list-community pull request #2162
Opened 2024-05-15 16:53 UTC by zhullyb

2024-06-14 04:33 UTC, rootmelo92118 requested changes

2024-06-14 04:33 UTC, rootmelo92118 commented on data/wps
> +kscord.com
Could you provide the evidence of it?

2024-06-15 00:55 UTC, Hyy2001X commented on data/wps
> +kscord.com
kscord.com
珠海金山办公软件有限公司
粤ICP备13015957号-20

2024-06-21 15:12 UTC, rootmelo92118 approved these changes

2024-06-21 15:12 UTC, merged

2026-06-28 15:28 UTC, MkQtS commented
这里实际添加的是 `kscord.com`，是一个未注册的无效域名，而 PR 标题以及备案号是属于 `ksord.com` 的