Update cnet
v2fly/domain-list-community pull request #2257
Opened 2024-07-22 05:02 UTC by User53464563

2024-07-25 09:40 UTC, KukiSa commented
`cnetnews.com.cn` ICP备案被注销，原备案号：京ICP备15039648号-3 北京第二十六维信息技术有限公司 Cnet科技资讯网

2024-07-26 14:14 UTC, rootmelo92118 commented
> `cnetnews.com.cn` ICP备案被注销，原备案号：京ICP备15039648号-3 北京第二十六维信息技术有限公司 Cnet科技资讯网

@User53464563

2024-07-26 14:14 UTC, rootmelo92118 requested changes
> `cnetnews.com.cn` ICP备案被注销，原备案号：京ICP备15039648号-3 北京第二十六维信息技术有限公司 Cnet科技资讯网

@User53464563

2024-07-26 16:18 UTC, IceCodeNew approved these changes

2024-07-26 16:18 UTC, IceCodeNew commented on data/cnet
> +cnet.co.kr
```suggestion
cnet.co.kr
cnet.com
cnet.de
```

2024-07-26 16:19 UTC, merged