Update apple
v2fly/domain-list-community pull request #2259
Opened 2024-07-22 07:25 UTC by Barry-SH

解决 https://github.com/v2fly/domain-list-community/issues/2228#issuecomment-2224726160

提取的方法和google那里一样。
https://github.com/v2fly/domain-list-community/pull/2229#issuecomment-2235761744

2024-07-26 14:21 UTC, IceCodeNew commented
不好意思，上个 pr 就忘了处理了。上周因为培训要忙，大概这周末可以忙完
pr 我先不承诺时间了，但下周的某个时间会处理

2024-07-26 14:58 UTC, IceCodeNew commented
你的自动化处理方法很好，但是对于打算改为进行子域名匹配的条目，容我再提以下几个要求吧：
1. 通过类似 https://github.com/owasp-amass/amass 的项目尝试进行子域名猜测，找到至少一个子域名来确认自己的猜测
2. 对每一项条目，挑选任意一个扫描到的子域名，尝试做一次 DNS 解析（注意国内国外解析结果可能不同）。通过这种抽查的方式确认子域名有 IP 解析到国内
3. 在整个 data 目录下搜索你要从 full: 改为 domain: 的条目，确认该条目没有出现在别的地方。做必要的去重和冲突处理 （比如 `full:gvt1-cn.com` 改为 `gvt1-cn.com`，那么应该在整个 data 目录下搜索 `gvt1-cn.com` 是否有在别的地方出现）

2024-07-26 14:59 UTC, IceCodeNew requested changes
你的自动化处理方法很好，但是对于打算改为进行子域名匹配的条目，容我再提以下几个要求吧：
1. 通过类似 https://github.com/owasp-amass/amass 的项目尝试进行子域名猜测，找到至少一个子域名来确认自己的猜测
2. 对每一项条目，挑选任意一个扫描到的子域名，尝试做一次 DNS 解析（注意国内国外解析结果可能不同）。通过这种抽查的方式确认子域名有 IP 解析到国内
3. 在整个 data 目录下搜索你要从 full: 改为 domain: 的条目，确认该条目没有出现在别的地方。做必要的去重和冲突处理 （比如 `full:gvt1-cn.com` 改为 `gvt1-cn.com`，那么应该在整个 data 目录下搜索 `gvt1-cn.com` 是否有在别的地方出现）

2024-07-28 08:17 UTC, Barry-SH commented
> 你的自动化处理方法很好，但是对于打算改为进行子域名匹配的条目，容我再提以下几个要求吧：
> 
> 1. 通过类似 https://github.com/owasp-amass/amass 的项目尝试进行子域名猜测，找到至少一个子域名来确认自己的猜测
> 2. 对每一项条目，挑选任意一个扫描到的子域名，尝试做一次 DNS 解析（注意国内国外解析结果可能不同）。通过这种抽查的方式确认子域名有 IP 解析到国内
> 3. 在整个 data 目录下搜索你要从 full: 改为 domain: 的条目，确认该条目没有出现在别的地方。做必要的去重和冲突处理 （比如 `full:gvt1-cn.com` 改为 `gvt1-cn.com`，那么应该在整个 data 目录下搜索 `gvt1-cn.com` 是否有在别的地方出现）

多谢指导。 
amass 我没有用过。好像用类似这个命令 `amass enum -passive -d owasp.org` ，可以查出来可能的子域名。 
有时间我会写个脚本来做上面检查，完成后会贴结果到这边。如果需要会修改这个PR。

2024-08-03 03:31 UTC, Barry-SH commented
@IceCodeNew 

我用amass试着在我环境下扫描。
比如 a1.mzstatic.com
```
$ docker run --rm --network=host -e http_proxy=http://127.0.0.1:10809 -e https_proxy=http://127.0.0.1:10809 -v /tmp/amass:/.config/amass/ caffix/amass enum -d a1.mzstatic.com
No assets were discovered

The enumeration has finished
```
会显示没有发现，同时我看了输出的log 文件 `amass.log`.
发现里面会有如下错误
```
03:16:15.820408 Sublist3rAPI: vertical request to service failed: Get "https://api.sublist3r.com/search.php?domain=a2.mzstatic.com": remote error: tls: internal error
03:16:16.003144 Greynoise: vertical request to service returned with status: 404 Not Found
03:16:16.597280 DNSHistory: vertical request to service returned with status code: 403 Forbidden
03:16:16.731770 Pulsedive: vertical request to service returned with status: 429 Too Many Requests
03:16:17.499706 Riddler: scrape: Get "https://riddler.io/search/exportcsv?q=pld:a2.mzstatic.com": EOF
03:16:20.709579 Arquivo: vertical request to service returned with status code: 400 Bad Request
03:16:22.911895 HAW: vertical request to service failed: Get "https://haw.nsk.hr/proxy.php?subject=keywords&start=undefined&q=a2.mzstatic.com": net/http: TLS handshake timeout
03:16:28.912069 Wayback: scrape: Get "https://web.archive.org/cdx/search/cdx?matchType=domain&fl=original&output=json&collapse=urlkey&url=a2.mzstatic.com": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
03:16:29.618646 Searx: scrape: Post "https://searx.info/search": EOF
03:16:39.871192 Yahoo: scrape: Get "https://search.yahoo.com/search?b=141&bct=0&p=site%3Aa2.mzstatic.com+-domain%3Awww.a2.mzstatic.com&pz=10&xargs=0": EOF
03:16:52.313860 CommonCrawl: scrape: Get "https://index.commoncrawl.org/CC-MAIN-2024-18-index?fl=url&output=json&url=%2A.a2.mzstatic.com": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
是否我可以忽略这个错误，认为 a1.mzstatic.com 是没有子域名的。这种还是用 Full的限定。

BTW，每个都要扫描会耗时比较久。

2024-08-03 08:03 UTC, Barry-SH commented
我试了下面这些，都是 “No assets were discovered” 的结果。
我现在怀疑，可能都没有子域名。用full指定是正确的。

```
a1.mzstatic.com
a2.mzstatic.com
a3.mzstatic.com
a4.mzstatic.com
a5.mzstatic.com
adcdownload.apple.com.akadns.net
adcdownload.apple.com
amp-api.media.apple.com
api-p-ap-c.smoot.apple.com
api-p-ap-d.smoot.apple.com
api-p-ap-e.smoot.apple.com
app-site-association.cdn-apple.com
appldnld.apple.com
appldnld.g.aaplimg.com
appleid.cdn-apple.com
apps.mzstatic.com
```

2024-08-05 02:31 UTC, IceCodeNew commented
> 是否我可以忽略这个错误，认为 a1.mzstatic.com 是没有子域名的。这种还是用 Full的限定。

你可以调高日志级别，看看是否有其他第三方引擎成功调用了。一部分调用失败没有关系
不过还是建议在跑 amass 的时候用专门的 vps 跑，有必要的话可能要放慢检查速度，或者分布到多台机器上跑

2024-08-05 09:42 UTC, Barry-SH commented
> > 是否我可以忽略这个错误，认为 a1.mzstatic.com 是没有子域名的。这种还是用 Full的限定。
> 
> 你可以调高日志级别，看看是否有其他第三方引擎成功调用了。

好的。我会检查一下。

> 一部分调用失败没有关系 不过还是建议在跑 amass 的时候用专门的 vps 跑，有必要的话可能要放慢检查速度，或者分布到多台机器上跑

我只有一个美国的VPS。没有多的VPS分布地跑这个。

2024-08-11 05:55 UTC, Barry-SH commented
> 你可以调高日志级别，看看是否有其他第三方引擎成功调用了。

这是在 amass/amass.log 内全部 log （docker run --rm --network=host -v /tmp/amass:/.config/amass/ caffix/amass enum -v -d a1.mzstatic.com。 我是直接在美国的VPS 上执行。)
可以看到 Querying 了很多，有部分返回是错误。所以应该结果是可信的。

```
05:44:35.660846 ZoomEye: check callback failed for the configuration
05:44:35.661455 360PassiveDNS: check callback failed for the configuration
05:44:35.661493 ASNLookup: check callback failed for the configuration
05:44:35.678758 Ahrefs: check callback failed for the configuration
05:44:35.699190 BeVigil: check callback failed for the configuration
05:44:35.699288 BigDataCloud: check callback failed for the configuration
05:44:35.699329 BinaryEdge: check callback failed for the configuration
05:44:35.720692 BufferOver: check callback failed for the configuration
05:44:35.720812 BuiltWith: check callback failed for the configuration
05:44:35.720859 C99: check callback failed for the configuration
05:44:35.720896 CIRCL: check callback failed for the configuration
05:44:35.720928 Censys: check callback failed for the configuration
05:44:35.720958 CertCentral: check callback failed for the configuration
05:44:35.721005 Chaos: check callback failed for the configuration
05:44:35.739860 DNSDB: check callback failed for the configuration
05:44:35.739985 DNSRepo: check callback failed for the configuration
05:44:35.740058 DNSlytics: check callback failed for the configuration
05:44:35.740090 Deepinfo: check callback failed for the configuration
05:44:35.740117 Detectify: check callback failed for the configuration
05:44:35.740202 FOFA: check callback failed for the configuration
05:44:35.740237 FacebookCT: check callback failed for the configuration
05:44:35.740273 FullHunt: check callback failed for the configuration
05:44:35.740337 GitHub: check callback failed for the configuration
05:44:35.740368 GitLab: check callback failed for the configuration
05:44:35.740492 Hunter: check callback failed for the configuration
05:44:35.740577 IPdata: check callback failed for the configuration
05:44:35.740605 IPinfo: check callback failed for the configuration
05:44:35.740632 IntelX: check callback failed for the configuration
05:44:35.740715 Netlas: check callback failed for the configuration
05:44:35.740737 ONYPHE: check callback failed for the configuration
05:44:35.740778 PassiveTotal: check callback failed for the configuration
05:44:35.740803 Pastebin: check callback failed for the configuration
05:44:35.740840 PentestTools: check callback failed for the configuration
05:44:35.740872 PublicWWW: check callback failed for the configuration
05:44:35.740935 Quake: check callback failed for the configuration
05:44:35.760569 SOCRadar: check callback failed for the configuration
05:44:35.760733 SecurityTrails: check callback failed for the configuration
05:44:35.760825 Shodan: check callback failed for the configuration
05:44:35.760883 Spamhaus: check callback failed for the configuration
05:44:35.761025 ThreatBook: check callback failed for the configuration
05:44:35.761126 VirusTotal: check callback failed for the configuration
05:44:35.761170 WhoisXMLAPI: check callback failed for the configuration
05:44:35.761248 Yandex: check callback failed for the configuration
05:44:35.761287 ZETAlytics: check callback failed for the configuration
05:44:35.863196 Querying Bing for a1.mzstatic.com subdomains
05:44:35.865565 Querying Active Crawl for a1.mzstatic.com subdomains
05:44:35.865926 Querying RapidDNS for a1.mzstatic.com subdomains
05:44:35.866248 Querying Riddler for a1.mzstatic.com subdomains
05:44:35.866597 Querying Searchcode for a1.mzstatic.com subdomains
05:44:35.866935 Querying CertSpotter for a1.mzstatic.com subdomains
05:44:35.867300 Querying Crtsh for a1.mzstatic.com subdomains
05:44:35.867586 Querying ThreatMiner for a1.mzstatic.com subdomains
05:44:35.867930 Querying Searx for a1.mzstatic.com subdomains
05:44:35.868105 Querying Mnemonic for a1.mzstatic.com subdomains
05:44:35.868123 Querying Ask for a1.mzstatic.com subdomains
05:44:35.868126 Querying Digitorus for a1.mzstatic.com subdomains
05:44:35.868138 Querying GrepApp for a1.mzstatic.com subdomains
05:44:35.868143 Querying Sublist3rAPI for a1.mzstatic.com subdomains
05:44:35.868146 Querying CommonCrawl for a1.mzstatic.com subdomains
05:44:35.868150 Querying Synapsint for a1.mzstatic.com subdomains
05:44:35.868159 Querying Arquivo for a1.mzstatic.com subdomains
05:44:35.868163 Querying Greynoise for a1.mzstatic.com subdomains
05:44:35.868168 Querying SubdomainCenter for a1.mzstatic.com subdomains
05:44:35.868172 Querying DNS SRV for a1.mzstatic.com subdomains
05:44:35.868190 Querying PKey for a1.mzstatic.com subdomains
05:44:35.868194 Querying Wayback for a1.mzstatic.com subdomains
05:44:35.868199 Querying DuckDuckGo for a1.mzstatic.com subdomains
05:44:35.868203 Querying Gists for a1.mzstatic.com subdomains
05:44:35.868212 Querying HackerOne for a1.mzstatic.com subdomains
05:44:35.868217 Querying SiteDossier for a1.mzstatic.com subdomains
05:44:35.868221 Querying DNSHistory for a1.mzstatic.com subdomains
05:44:35.868225 Querying HyperStat for a1.mzstatic.com subdomains
05:44:35.868233 Querying Yahoo for a1.mzstatic.com subdomains
05:44:35.868237 Querying Baidu for a1.mzstatic.com subdomains
05:44:35.868241 Querying Brute Forcing for a1.mzstatic.com subdomains
05:44:35.868249 Querying Google for a1.mzstatic.com subdomains
05:44:35.868254 Querying HAW for a1.mzstatic.com subdomains
05:44:35.868267 Querying Pulsedive for a1.mzstatic.com subdomains
05:44:35.868270 Querying URLScan for a1.mzstatic.com subdomains
05:44:35.868275 Querying HackerTarget for a1.mzstatic.com subdomains
05:44:35.868280 Querying LeakIX for a1.mzstatic.com subdomains
05:44:35.868288 Querying Maltiverse for a1.mzstatic.com subdomains
05:44:35.868293 Querying AbuseIPDB for a1.mzstatic.com subdomains
05:44:35.868297 Querying Active DNS for a1.mzstatic.com subdomains
05:44:35.868309 Querying AnubisDB for a1.mzstatic.com subdomains
05:44:35.868316 Querying DNSDumpster for a1.mzstatic.com subdomains
05:44:35.868320 Querying DNSSpy for a1.mzstatic.com subdomains
05:44:35.868324 Querying UKWebArchive for a1.mzstatic.com subdomains
05:44:35.868328 Querying AlienVault for a1.mzstatic.com subdomains
05:44:36.889566 Riddler: https://riddler.io/search/exportcsv?q=pld:a1.mzstatic.com: Get "https://riddler.io/search/exportcsv?q=pld:a1.mzstatic.com": dial tcp: lookup riddler.io: Name has no usable address
05:44:36.889658 Riddler: scrape: Get "https://riddler.io/search/exportcsv?q=pld:a1.mzstatic.com": dial tcp: lookup riddler.io: Name has no usable address
05:44:37.211421 Greynoise: vertical request to service returned with status: 404 Not Found
05:44:37.907006 Searx: https://procurx.pt/search: Post "https://procurx.pt/search": dial tcp: lookup procurx.pt: no such host
05:44:37.907104 Searx: scrape: Post "https://procurx.pt/search": dial tcp: lookup procurx.pt: no such host
05:44:37.909538 DNSHistory: vertical request to service returned with status code: 403 Forbidden
05:44:38.070912 Sublist3rAPI: https://api.sublist3r.com/search.php?domain=a1.mzstatic.com: Get "https://api.sublist3r.com/search.php?domain=a1.mzstatic.com": remote error: tls: internal error
05:44:38.071032 Sublist3rAPI: vertical request to service failed: Get "https://api.sublist3r.com/search.php?domain=a1.mzstatic.com": remote error: tls: internal error
05:44:38.122290 Pulsedive: vertical request to service returned with status: 429 Too Many Requests
05:44:41.974895 Arquivo: vertical request to service returned with status code: 400 Bad Request
```

2024-08-11 05:57 UTC, Barry-SH commented
`docker run --rm --network=host -v /tmp/amass:/.config/amass/ caffix/amass enum -v -d a1.mzstatic.com`

这个在美国VPS上执行没有报告“No assets were discovered”，但是根据如下的结果，我的理解应该也是没有发现子域名。
```
Querying Bing for a1.mzstatic.com subdomains
Querying Active Crawl for a1.mzstatic.com subdomains
Querying RapidDNS for a1.mzstatic.com subdomains
Querying Riddler for a1.mzstatic.com subdomains
Querying Searchcode for a1.mzstatic.com subdomains
Querying CertSpotter for a1.mzstatic.com subdomains
Querying Crtsh for a1.mzstatic.com subdomains
Querying ThreatMiner for a1.mzstatic.com subdomains
Querying Searx for a1.mzstatic.com subdomains
Querying Mnemonic for a1.mzstatic.com subdomains
Querying Ask for a1.mzstatic.com subdomains
Querying Digitorus for a1.mzstatic.com subdomains
Querying GrepApp for a1.mzstatic.com subdomains
Querying Sublist3rAPI for a1.mzstatic.com subdomains
Querying CommonCrawl for a1.mzstatic.com subdomains
Querying Synapsint for a1.mzstatic.com subdomains
Querying Arquivo for a1.mzstatic.com subdomains
Querying Greynoise for a1.mzstatic.com subdomains
Querying SubdomainCenter for a1.mzstatic.com subdomains
Querying DNS SRV for a1.mzstatic.com subdomains
Querying PKey for a1.mzstatic.com subdomains
Querying Wayback for a1.mzstatic.com subdomains
Querying DuckDuckGo for a1.mzstatic.com subdomains
Querying Gists for a1.mzstatic.com subdomains
Querying HackerOne for a1.mzstatic.com subdomains
Querying SiteDossier for a1.mzstatic.com subdomains
Querying DNSHistory for a1.mzstatic.com subdomains
Querying HyperStat for a1.mzstatic.com subdomains
Querying Yahoo for a1.mzstatic.com subdomains
Querying Baidu for a1.mzstatic.com subdomains
Querying Brute Forcing for a1.mzstatic.com subdomains
Querying Google for a1.mzstatic.com subdomains
Querying HAW for a1.mzstatic.com subdomains
Querying Pulsedive for a1.mzstatic.com subdomains
Querying URLScan for a1.mzstatic.com subdomains
Querying HackerTarget for a1.mzstatic.com subdomains
Querying LeakIX for a1.mzstatic.com subdomains
Querying Maltiverse for a1.mzstatic.com subdomains
Querying AbuseIPDB for a1.mzstatic.com subdomains
Querying Active DNS for a1.mzstatic.com subdomains
Querying AnubisDB for a1.mzstatic.com subdomains
Querying DNSDumpster for a1.mzstatic.com subdomains
Querying DNSSpy for a1.mzstatic.com subdomains
Querying UKWebArchive for a1.mzstatic.com subdomains
Querying AlienVault for a1.mzstatic.com subdomains
a1.mzstatic.com (FQDN) --> cname_record --> a1.mzstatic.itunes-apple.com.akadns.net (FQDN)
a1.mzstatic.itunes-apple.com.akadns.net (FQDN) --> cname_record --> mzstatic.com.edgekey.net (FQDN)

The enumeration has finished
```

2024-08-17 07:57 UTC, Barry-SH commented
目前我在美国的VPS 上执行 amass， 有下面的domain返回子domain

- iadsdk.apple.com
   ```
   ca.iadsdk.apple.com (FQDN) --> cname_record --> iadsdk.apple.com.akadns.net (FQDN)
   cs.iadsdk.apple.com (FQDN) --> cname_record --> iadsdk.apple.com.edgekey.net (FQDN)
   cf.iadsdk.apple.com (FQDN) --> cname_record --> iadsdk.apple.com (FQDN)
   ```
- itunes.apple.com
   ```
   mt-ingestion-service-mr22.itunes.apple.com (FQDN) --> cname_record --> mt-ingestion-service-mr22.itunes-apple.com.akadns.net (FQDN)
   buy.itunes.apple.com (FQDN) --> cname_record --> buy.itunes-apple.com.akadns.net (FQDN)
   myapp.itunes.apple.com (FQDN) --> cname_record --> myapp-cdn.itunes-apple.com.akadns.net (FQDN)
   p26-buy.itunes.apple.com (FQDN) --> cname_record --> p26-buy.itunes-apple.com.akadns.net (FQDN)
   itunesu-assets.itunes.apple.com (FQDN) --> cname_record --> itunes.assets.itunes.com.edgekey.net (FQDN)
   p16-buy.itunes.apple.com (FQDN) --> cname_record --> p16-buy.itunes-apple.com.akadns.net (FQDN)
   vocabulary.itunes.apple.com (FQDN) --> cname_record --> itunes.apple.com.edgekey.net (FQDN)
   siri-search.itunes.apple.com (FQDN) --> cname_record --> siri-search.itunes-apple.com.akadns.net (FQDN)
   p33-buy.itunes.apple.com (FQDN) --> cname_record --> p33-buy.itunes-apple.com.akadns.net (FQDN)
   np.itunes.apple.com (FQDN) --> cname_record --> np-cdn.itunes-apple.com.akadns.net (FQDN)
   pd.itunes.apple.com (FQDN) --> cname_record --> pd-cdn.itunes-apple.com.akadns.net (FQDN)
   pd-nk.itunes.apple.com (FQDN) --> cname_record --> pd-nk-cdn.itunes-apple.com.akadns.net (FQDN)
   p12-buy.itunes.apple.com (FQDN) --> cname_record --> p12-buy.itunes-apple.com.akadns.net (FQDN)
   p19-buy.itunes.apple.com (FQDN) --> cname_record --> p19-buy.itunes-apple.com.akadns.net (FQDN)
   ld-7.itunes.apple.com (FQDN) --> cname_record --> ld-7.itunes-apple.com.akadns.net (FQDN)
   ax.init.itunes.apple.com (FQDN) --> cname_record --> ax.init-cdn.itunes-apple.com.akadns.net (FQDN)
   p11-buy.itunes.apple.com (FQDN) --> cname_record --> p11-buy.itunes-apple.com.akadns.net (FQDN)
   p35-buy.itunes.apple.com (FQDN) --> cname_record --> p35-buy.itunes-apple.com.akadns.net (FQDN)
   analytics-st.itunes.apple.com (FQDN) --> cname_record --> analytics-st.itunes-apple.com.akadns.net (FQDN)
   ld-5.itunes.apple.com (FQDN) --> cname_record --> ld-5.itunes-apple.com.akadns.net (FQDN)
   p50-buy.itunes.apple.com (FQDN) --> cname_record --> p50-buy.itunes-apple.com.akadns.net (FQDN)
   client-api.itunes.apple.com (FQDN) --> cname_record --> client-api-cdn.itunes-apple.com.akadns.net (FQDN)
   tf-feedback.itunes.apple.com (FQDN) --> cname_record --> tf-feedback-geo.itunes-apple.com.akadns.net (FQDN)
   contentdelivery.itunes.apple.com (FQDN) --> cname_record --> contentdelivery.itunes-apple.com.akadns.net (FQDN)
   ld-4.itunes.apple.com (FQDN) --> cname_record --> ld-4.itunes-apple.com.akadns.net (FQDN)
   uic.itunes.apple.com (FQDN) --> cname_record --> festival.itunes.apple.com.edgekey.net (FQDN)
   genius-upload.itunes.apple.com (FQDN) --> cname_record --> genius-upload.itunes-apple.com.akadns.net (FQDN)
   client-api-cdn.itunes-apple.com.akadns.net (FQDN) --> cname_record --> client-api.itunes.apple.com.edgesuite.net (FQDN)
   ax.init-cdn.itunes-apple.com.akadns.net (FQDN) --> cname_record --> ax.init.itunes.apple.com.edgesuite.net (FQDN)
   np-cdn.itunes-apple.com.akadns.net (FQDN) --> cname_record --> np.itunes.apple.com.edgesuite.net (FQDN)
   np-edge.itunes.apple.com (FQDN) --> cname_record --> np-edge-cdn.itunes-apple.com.akadns.net (FQDN)
   apptrailers.itunes.apple.com (FQDN) --> cname_record --> apptrailers.itunes.g.aaplimg.com (FQDN)
   downloaddispatch.itunes.apple.com (FQDN) --> cname_record --> downloaddispatch-cdn.itunes-apple.com.akadns.net (FQDN)
   widgets.itunes.apple.com (FQDN) --> cname_record --> linkmaker.itunes.apple.com.edgekey.net (FQDN)
   hls.itunes.apple.com (FQDN) --> cname_record --> hls.itunes-apple.com.akadns.net (FQDN)
   play-edge-skrdc.itunes.apple.com (FQDN) --> cname_record --> sk00p00-daiquiriexternal-nlb-e7f41acb56c50533.elb.eu-north-1.amazonaws.com (FQDN)
   p5-buy.itunes.apple.com (FQDN) --> cname_record --> p5-buy.itunes-apple.com.akadns.net (FQDN)
   p53-buy.itunes.apple.com (FQDN) --> cname_record --> p53-buy.itunes-apple.com.akadns.net (FQDN)
   sc.itunes.apple.com (FQDN) --> cname_record --> sc.itunes.apple.com.akadns.net (FQDN)
   commerceproxy.itunes.apple.com (FQDN) --> cname_record --> commerceproxy.itunes.v.aaplimg.com (FQDN)
   uts-api-siri.itunes.apple.com (FQDN) --> cname_record --> uts-api-siri.itunes-apple.com.akadns.net (FQDN)
   misc-assets.itunes.apple.com (FQDN) --> cname_record --> misc-assets.itunes-apple.com.akadns.net (FQDN)
   p45-buy.itunes.apple.com (FQDN) --> cname_record --> p45-buy.itunes-apple.com.akadns.net (FQDN)
   aod.itunes.apple.com (FQDN) --> cname_record --> aod.itunes.g.aaplimg.com (FQDN)
   apptrailers-ssl.itunes.apple.com (FQDN) --> cname_record --> apptrailers-ssl.itunes-apple.com.akadns.net (FQDN)
   np-edge-cdn.itunes-apple.com.akadns.net (FQDN) --> cname_record --> np-edge.itunes.apple.com.edgesuite.net (FQDN)
   du-fuse.itunes.apple.com (FQDN) --> cname_record --> du-fuse.v.aaplimg.com (FQDN)
   silverbullet-external-admin-itms6.itunes.apple.com (FQDN) --> a_record --> 17.176.249.190 (IPAddress)
   segment-service-notification-partner.itunes.apple.com (FQDN) --> cname_record --> commerceprodqaproxy.itunes.v.aaplimg.com (FQDN)
   itmsls-itms5.itunes.apple.com (FQDN) --> a_record --> 17.176.248.32 (IPAddress)
   p48-buy.itunes.apple.com (FQDN) --> cname_record --> p48-buy.itunes-apple.com.akadns.net (FQDN)
   pv-rss.itunes.apple.com (FQDN) --> a_record --> 17.142.160.48 (IPAddress)
   genius-2.itunes.apple.com (FQDN) --> cname_record --> genius-2.itunes-apple.com.akadns.net (FQDN)
   itmsls-itms8.itunes.apple.com (FQDN) --> a_record --> 17.176.251.16 (IPAddress)
   device-capabilities-pv.itunes.apple.com (FQDN) --> a_record --> 17.110.232.21 (IPAddress)
   st-cb-carrier.itunes.apple.com (FQDN) --> a_record --> 17.173.66.221 (IPAddress)
   silverbullet-external-itms9.itunes.apple.com (FQDN) --> a_record --> 17.176.237.181 (IPAddress)
   itms6-srvspartner.itunes.apple.com (FQDN) --> a_record --> 17.176.249.219 (IPAddress)
   commercegateway-sandbox.itunes.apple.com (FQDN) --> cname_record --> commercegateway-sandbox.itunes-apple.com.akadns.net (FQDN)
   mr00-cls-ingest.itunes.apple.com (FQDN) --> a_record --> 17.110.232.98 (IPAddress)
   st00-cls-iosclient.itunes.apple.com (FQDN) --> a_record --> 17.173.66.31 (IPAddress)
   p32-buy.itunes.apple.com (FQDN) --> cname_record --> p32-buy.itunes-apple.com.akadns.net (FQDN)
   cls-ingest.itunes.apple.com (FQDN) --> cname_record --> cls-ingest.education-apple.com.akadns.net (FQDN)
   itmsls-itms9.itunes.apple.com (FQDN) --> a_record --> 17.176.237.28 (IPAddress)
   payments-partner.itunes.apple.com (FQDN) --> cname_record --> payments-partner.itunes-apple.com.akadns.net (FQDN)
   silverbullet-external-admin-itms5.itunes.apple.com (FQDN) --> a_record --> 17.176.248.214 (IPAddress)
   np-edge.itunes.apple.com.edgesuite.net (FQDN) --> cname_record --> a1863.dscw154.akamai.net (FQDN)
   linkmaker.itunes.apple.com.edgekey.net (FQDN) --> cname_record --> e3894.dsce9.akamaiedge.net (FQDN)
   feeds.itunes.apple.com (FQDN) --> cname_record --> static.itunes-apple.com.akadns.net (FQDN)
   p10-buy.itunes.apple.com (FQDN) --> cname_record --> p10-buy.itunes-apple.com.akadns.net (FQDN)
   silverbullet-external-admin-itms8.itunes.apple.com (FQDN) --> a_record --> 17.176.251.179 (IPAddress)
   mr-ed-video-service.itunes.apple.com (FQDN) --> a_record --> 17.124.184.76 (IPAddress)
   ipsadapter-itms6-inpartner-boku.itunes.apple.com (FQDN) --> a_record --> 17.176.249.201 (IPAddress)
   video.itunes.apple.com (FQDN) --> cname_record --> video.itunes.g.aaplimg.com (FQDN)
   silverbullet-external-itms5.itunes.apple.com (FQDN) --> a_record --> 17.176.248.213 (IPAddress)
   cb-carrier-prod-st-ext.itunes.apple.co [...]

2024-08-17 08:14 UTC, IceCodeNew commented
> 在整个 data 目录下搜索你要从 full: 改为 domain: 的条目，确认该条目没有出现在别的地方。做必要的去重和冲突处理 （比如 full:gvt1-cn.com 改为 gvt1-cn.com，那么应该在整个 data 目录下搜索 gvt1-cn.com 是否有在别的地方出现）

别忘了这个哈~pr准备好了就解除草稿状态拉我 review 吧

2024-08-17 08:16 UTC, Barry-SH commented
@IceCodeNew 

每个domain我选了第一个子域，都可以在国内解释出IP地址。
我重新提交了PR只移去那些确定有子域的"full:"。

2024-08-17 08:17 UTC, IceCodeNew commented
> 都可以在国内解释出IP地址

这句话需要明确一下，是解析记录的 ip 可以查到归属于国内吗？

2024-08-17 08:20 UTC, Barry-SH commented
> 这句话需要明确一下，是解析记录的 ip 可以查到归属于国内吗？

还要求解析的IP也是国内的？我再确认一下。

2024-08-17 08:31 UTC, Barry-SH commented
@IceCodeNew 

下面子域解析的地址是美国的.
- itunes.apple.com
  mt-ingestion-service-mr22.itunes-apple.com.akadns.net (17.120.252.13)  
  
- store.apple.com
  secure6.store.apple.com (17.8.129.112)
  
 - xp.apple.com
   daf-internal.xp.apple.com (17.56.10.41)
 
 不好意思，我有个疑问，国内DNS解释出IP地址是国外的也不行？
 我的理解“@cn” 意思可以通过国内DNS 解析，不用通过代理走国外DNS解析，我的理解是错的？

2024-08-17 08:34 UTC, IceCodeNew commented
> 我的理解“@cn” 意思可以通过国内DNS 解析，不用通过代理走国外DNS解析，我的理解是错的？

不是的，`@cn` 表示这个域名可以解析到国内的服务器

2024-08-17 08:44 UTC, IceCodeNew commented
> - `accelerated-domains.china.conf`: General domains to be accelerated.
> 
>   These domains have a better resolving speed and/or result when using a Chinese DNS server.
> 
>   To determine if a domain is eligible, one of the criteria below must be met:
> 
>  - The domain's NS server is located in China mainland.
> 
>  - The domain will resolve to an IP located in China mainland when using a Chinese DNS server, but _not_ always do when using a foreign DNS server (For example, CDN accelerated sites that have node in China). This however does _not_ include those having node _near_ China mainland, like in Japan, Hong Kong, Taiwan, etc.
> 
>   Please don't add subdomains if the top domain is already in the list. This includes all .cn domains which are already matched by the `/cn/` rule.
> 
> - `apple.china.conf`: Apple domains to be accelerated.
> 
>   Some ISPs (often smaller ones) have problem accessing Apple's assets using their China mainland CDN servers. Please consider remove this file if that happens to you. See #156 for some more info.

这个事是这样的，上游维护 accelerated-domains.china.conf 这个列表的时候只要一个域名满足两个条件中任意一个就可以被加到列表中：
1. 域名的 NS 服务器在国内
2. 域名有解析地址指向国内的服务器

apple.china.conf 不是默认安装的列表，而是用户可以选择启用的。这个列表只明确了要包括那些可以通过走国内的 CDN 来获得更好的访问体验的域名，并不一定和 accelerated-domains.china.conf 列表使用一样的维护标准
即便使用一样的维护标准，apple.china.conf 里的域名也不保证和这个项目中 `@cn` 标签的含义一样。因为域名可以不解析到国内的服务器上，只要 NS 服务器在国内就行了

从这个角度来说，历史上引入上游这个列表本身就不是很合适。我们现在能做的只有加高审核标准，不要进一步滥用 `@cn` 标签了

2024-08-17 09:08 UTC, Barry-SH commented
> 不是的，`@cn` 表示这个域名可以解析到国内的服务器

明白了！多谢！

### 去重
```
barry-xu@Test-Laptop:~/Work/domain-list-community$ grep -Rni 'iadsdk.apple.com' *
data/apple:873:iadsdk.apple.com @cn
data/apple-ads:2:iadsdk.apple.com @ads
```
这个出现在 apple-ads中，是否我应该直接在apple这个文件中注释掉 iadsdk.apple.com ？ 由apple-ads负责

--- 

```
barry-xu@Test-Laptop:~/Work/domain-list-community$ grep -Rni 'itunes.apple.com' *
data/apple:748:full:amp-api-edge-lb-cn.itunes-apple.com.akadns.net @cn
data/apple:749:full:amp-api-edge-lb.itunes-apple.com.akadns.net @cn
data/apple:753:full:aod.itunes.apple.com @cn
data/apple:755:full:apptrailers.itunes.apple.com @cn
data/apple:756:full:bag.itunes.apple.com @cn
data/apple:757:full:bookkeeper.itunes.apple.com @cn
data/apple:758:full:client-api.itunes.apple.com @cn
data/apple:759:full:cma.itunes.apple.com @cn
data/apple:762:full:downloaddispatch.itunes.apple.com @cn
data/apple:767:full:inappcheck-cn.itunes-apple.com.akadns.net @cn
data/apple:768:full:inappcheck-lb.itunes-apple.com.akadns.net @cn
data/apple:769:full:inappcheck.itunes.apple.com @cn
data/apple:770:full:init.itunes.apple.com @cn
data/apple:773:full:iosapps.itunes.apple.com @cn
data/apple:777:full:osxapps.itunes.apple.com @cn
data/apple:778:full:pd.itunes.apple.com @cn
data/apple:779:full:play.itunes.apple.com @cn
data/apple:780:full:se-edge.itunes.apple.com @cn
data/apple:781:full:se2.itunes.apple.com @cn
data/apple:782:full:search.itunes.apple.com @cn
data/apple:783:full:sf-api-token-service.itunes.apple.com @cn
data/apple:784:full:sp.itunes.apple.com @cn
data/apple:785:full:streamingaudio.itunes.apple.com @cn
data/apple:786:full:su.itunes.apple.com @cn
data/apple:787:full:sync.itunes.apple.com @cn
data/apple:788:full:upp.itunes.apple.com @cn
data/apple:901:full:itunes-apple.com.akadns.net @cn
data/apple:902:itunes.apple.com @cn
data/apple-update:10:ns.itunes.apple.com
data/itunes:22:itunes-apple.com.akadns.net
data/category-entertainment:91:bag.itunes.apple.com
data/category-entertainment:92:bookeeper.itunes.apple.com
```
itunes.apple.com 的子域在其它地方定义过，而且上面也发现子域里面有IP地址是在国外，所以我应该注释掉 “itunes.apple.com @cn“ ？

--- 

```
barry-xu@Test-Laptop:~/Work/domain-list-community$ grep -Rni 'music.apple.com' *
data/apple:774:full:js-cdn.music.apple.com @cn
data/apple:908:music.apple.com @cn
```
根据 https://github.com/v2fly/domain-list-community/pull/2259#issuecomment-2294772670，music.apple.com 下面有很多子域，有些地址是国内的，有些地址是国外的，那写 `music.apple.com @cn` 就不合适了，是不是也该注释掉 ？

--- 

store.apple.com 有子域解释是国外IP地址，所以 `store.apple.com @cn` 也不合适，应该注释掉 ？

---
```
barry-xu@Test-Laptop:~/Work/domain-list-community$ grep -Rni 'support.apple.com' *
data/apple:775:full:km.support.apple.com @cn
data/apple:940:support.apple.com @cn
```
加上amass发现的（下面的）都是中国的地址，rss.support.apple.com解析出是香港的。是否我可以删除  `data/apple:775:full:km.support.apple.com @cn` ？
```
km.support.apple.com (FQDN) --> cname_record --> support-china.apple-support.akadns.net (FQDN)
rss.support.apple.com (FQDN) --> cname_record --> support.apple.com.edgekey.net (FQDN)
www.support.apple.com (FQDN) --> cname_record --> support.apple.com (FQDN)
```
---

xp.apple.com 有子域解释出是国外地址，所以 `xp.apple.com @cn` 也不合适，应该注释掉 ？

2024-08-17 09:39 UTC, IceCodeNew commented
> 这个出现在 apple-ads中，是否我应该直接在apple这个文件中注释掉 iadsdk.apple.com ？ 由apple-ads负责

查了一下这个域名是 https://github.com/v2fly/domain-list-community/commit/636482115771fb7e1c03f77ec58d49294e826cea 引入的，没有说明背景。但是在网上大致搜了下，屏蔽整个域名可能也是合理的。你可以只保留 apple-ads 中的记录

2024-08-17 23:35 UTC, Barry-SH commented
@IceCodeNew 

多谢，详细的回复。

>> 加上amass发现的（下面的）都是中国的地址，rss.support.apple.com 解析出是香港的。是否我可以删除 data/apple:775:full:km.support.apple.com https://github.com/cn ？
>
> 没看懂。要注意在美国 vps 上解析的结果和国内解析的结果可能不一样。

我是用国内的DNS解释出的IP 地址，然后用这个网站https://tool.lu/ip/ 查询IP 地址的归属地。

> xp.apple.com 有子域解释出是国外地址，所以 xp.apple.com https://github.com/cn 也不合适，应该注释掉 ？
>
> 你这个结论是根据在美国 vps 上的解析结果来的吗？那可能证据还不充分

这个也是用上面同样的方式查询归属地，没有在美国的vps上操作。

由于今天开始要和家人出去一周无法用电脑，等下周末，我按照你上面说的再提交一版修正。

2024-08-24 06:06 UTC, Barry-SH commented
@IceCodeNew 

我已经根据你的意见修改了。“@cn” 是指中国大陆对吧！前面我把IP地址属于香港也算进取了。
[887d3d7](https://github.com/v2fly/domain-list-community/pull/2259/commits/887d3d7b5a1507eea3a010bb661bc88f31094bce) 里面
```
full:pd-nk.itunes.apple.com @cn
full:myapp.itunes.apple.com @cn
full:tf-feedback.itunes.apple.com @cn
full:np-edge.itunes.apple.com @cn
full:misc-assets.itunes.apple.com @cn
full:www.support.apple.com @cn
full:play.music.apple.com @cn
full:auth.music.apple.com @cn
full:amp-api.music.apple.com @cn
```
这些我已经确认国内DNS解析的IP地址也都在大陆的。

2024-08-26 04:10 UTC, IceCodeNew approved these changes

2024-08-26 04:11 UTC, merged