Create category-bank-jp
v2fly/domain-list-community pull request #2276
Opened 2024-08-01 18:52 UTC by ImAubrey

2024-08-07 07:41 UTC, rootmelo92118 requested changes

2024-08-07 07:41 UTC, rootmelo92118 commented on data/category-bank-jp
Please include it to relevant category.

2024-09-05 08:50 UTC, IceCodeNew approved these changes

2024-09-05 08:50 UTC, IceCodeNew commented on data/category-bank-jp
That is fine.

2024-09-05 08:51 UTC, merged