Add regex for some porn sites (category-porn)
v2fly/domain-list-community pull request #2344
Opened 2024-09-17 06:55 UTC by Carrot3628

2024-09-18 14:41 UTC, Amukev approved these changes

2024-09-20 05:55 UTC, rootmelo92118 requested changes
sort it. and please submit the source.

2024-09-20 05:59 UTC, Amukev approved these changes

2024-09-20 06:33 UTC, rootmelo92118 commented
@Amukev The contributor does not sort the regular expression which had been submitted.

2024-10-13 10:54 UTC, Amukev approved these changes

2024-10-13 10:55 UTC, Amukev requested changes

2024-10-13 10:55 UTC, Amukev commented on data/category-porn
> +regexp:(^|\.)x9av\d+\.com$
```suggestion
regexp:(^|\.)x9av\d+\.com$
```

2024-10-13 11:03 UTC, Amukev commented on data/category-porn
> +regexp:(^|\.)x9av\d+\.com$
[]()

2024-10-13 11:03 UTC, Amukev commented on data/category-porn
> +regexp:(^|\.)x9av\d+\.com$
[]()

2024-11-04 07:01 UTC, closed without merging