Adding Supercell and separating Google search
v2fly/domain-list-community pull request #2371
Opened 2024-10-11 13:53 UTC by molink36

Google search domains are separated from other domains.
Supercell domains are added.

2024-11-04 07:06 UTC, rootmelo92118 requested changes

2024-11-04 07:06 UTC, rootmelo92118 commented on data/google
The domains that you removed are not only for search. They already have a lot of sub domains on them.

2024-11-07 08:36 UTC, molink36 commented
Dear @rootmelo92118

Thank you. You are right.
Changes are applied.

2024-12-21 10:48 UTC, rootmelo92118 approved these changes

2024-12-21 10:48 UTC, merged