Add Mobile Repair Domains
v2fly/domain-list-community pull request #2391
Opened 2024-11-01 13:14 UTC by fakhamatia

2024-11-04 06:51 UTC, rootmelo92118 requested changes
Please include them in relevant category.

2024-11-04 09:27 UTC, fakhamatia commented
> Please include them in relevant category.

What theme?
I include `borneoschematics` and `z3x-team` in `category-mobile-repair`.

2024-12-18 08:55 UTC, fakhamatia commented
> > Please include them in relevant category.
> 
> What them? I include `borneoschematics` and `z3x-team` in `category-mobile-repair`.

@rootmelo92118

2024-12-21 10:12 UTC, rootmelo92118 approved these changes

2024-12-21 10:12 UTC, merged