Create daily action to update adobe-activation
v2fly/domain-list-community pull request #2417
Opened 2024-11-26 10:48 UTC by zetaloop

Closes: #2394

This pull request introduces a new GitHub Actions workflow to automate the update of the Adobe Activation list. The workflow is scheduled to run daily and includes steps to check for changes and update the list if necessary.

2025-02-03 13:06 UTC, zetaloop commented
Hi, just a gentle reminder—when you have a moment, could you please review this PR? Thank you!
@IceCodeNew

2025-02-04 02:56 UTC, IceCodeNew commented
> Hi, just a gentle reminder—when you have a moment, could you please review this PR? Thank you! @IceCodeNew

I am traveling, sorry this PR will not be reviewed for the following week.

2025-02-04 03:03 UTC, IceCodeNew requested changes

2025-02-04 03:03 UTC, IceCodeNew commented on .github/workflows/adobe-activation.yml
> +          curl -sSL https://raw.githubusercontent.com/ignaciocastro/a-dove-is-dumb/main/pihole.txt -o new-pihole.txt
By the time I checked this source, it was updated within 24hrs, which is good.
But I am not sure this source will get long enough maintenance, that is a NO-GO to me to use a third-party source.

BTW, you have to make sure that we will not violate their open-source license. You might just forget to mention it in this PR.

2025-02-04 03:03 UTC, IceCodeNew commented on data/adobe-activation
> +1b9khekel6.adobe.io
It makes no point in abusing the `domain:` suffix, these domains should be matched with the `full:` suffix.

2025-02-04 03:29 UTC, IceCodeNew commented
You are suggested to maintain a fork of this project.
I am strongly against this PR being merged, this project can not afford to be DMCA-takedown.

I would appreciate it if you could see my point.

2025-02-04 09:36 UTC, zetaloop commented
Thank you for the feedback. I understand your concerns and will close this PR.

2025-02-04 09:36 UTC, closed without merging