Add 12306 splash screen ad domain
v2fly/domain-list-community pull request #2438
Opened 2024-12-15 13:57 UTC by lim-kim930

2024-12-21 10:29 UTC, rootmelo92118 requested changes
Please provide the evidence of it.

2024-12-21 11:39 UTC, lim-kim930 commented
Using packet capture software, it's easy to identify that the ad domain is ad.12306.cn:

https://github.com/user-attachments/assets/ce54e648-073c-42cb-9d4c-79f0d64f9619


If you need a more intuitive comparison of the app's splash screen before and after the domain is blocked, I can provide it as well. However, due to caching issues, it might not be entirely accurate.

2025-02-07 13:27 UTC, lim-kim930 commented
@Loyalsoldier  @rootmelo92118 

Guys, reviewwwww😰

2025-02-23 16:38 UTC, rootmelo92118 approved these changes

2025-02-23 16:38 UTC, merged