add garena
v2fly/domain-list-community pull request #244
Opened 2020-10-07 15:48 UTC by ajiou

2020-10-07 16:00 UTC, IceCodeNew requested changes
我可能没有正确地把握到这个站点的性质（我对电竞不熟悉）
但看起来这个分类文件应该包括在 entertainment 文件里。

2020-10-07 16:05 UTC, parasomn1a requested changes

2020-10-07 16:05 UTC, parasomn1a commented on data/garena
> +dlmobilegarena-a.akamaihd.net
或许在前面加上 `full:` 会更好？

2020-10-07 16:18 UTC, IceCodeNew approved these changes

2020-10-08 02:11 UTC, parasomn1a approved these changes

2020-10-08 02:16 UTC, merged