Create Antivirus Category and Kaspersky
v2fly/domain-list-community pull request #2445
Opened 2024-12-21 11:41 UTC by fakhamatia

2025-03-07 17:06 UTC, fakhamatia commented
Hello @rootmelo92118

2025-03-26 07:14 UTC, rootmelo92118 requested changes
Please put the category `category-antivirus` into a suitable category.

2025-03-26 10:23 UTC, fakhamatia commented
> Please put the category `category-antivirus` into a suitable category.

It's already done.

2025-04-19 10:03 UTC, IceCodeNew commented
After @rootmelo92118 finish reviewing, pls let me know. I would like to be envolved and to do the final decision on this PR.

2025-04-19 14:53 UTC, rootmelo92118 commented
> > Please put the category `category-antivirus` into a suitable category.
> 
> It's already done.

I mean... The category `category-antivirus` is not included in other category. If you don't do that, this category will never be used. So, please include it in the category which is already existed in this repository.

2025-04-20 07:53 UTC, fakhamatia commented
> I mean... The category `category-antivirus` is not included in other category. If you don't do that, this category will never be used. So, please include it in the category which is already existed in this repository.

@rootmelo92118 
Please guide me in which category should I put it?

2025-08-27 06:09 UTC, fakhamatia commented
> > > Please put the category `category-antivirus` into a suitable category.
> > 
> > 
> > It's already done.
> 
> I mean... The category `category-antivirus` is not included in other category. If you don't do that, this category will never be used. So, please include it in the category which is already existed in this repository.

Please guide. Where should I put the antivirus category?

2025-08-29 12:22 UTC, Loyalsoldier commented
@fakhamatia 

You'd better add more antivirus products into `category-antivirus` and include it into `geolocation-!cn`.

2025-10-17 14:22 UTC, closed without merging