Add cryptomus
v2fly/domain-list-community pull request #2459
Opened 2024-12-28 15:18 UTC by closehandle

https://cryptomus.com

2025-02-23 17:08 UTC, rootmelo92118 requested changes
If it only just has one domain, you don't need to create a new category.

2025-02-26 15:39 UTC, rootmelo92118 commented on data/category-cryptocurrency
> +include:cryptomus
Remove it.

2025-02-27 22:42 UTC, closehandle commented on data/category-cryptocurrency
> +include:cryptomus
Oh no, i forget about it, now removed.

2025-03-02 15:36 UTC, rootmelo92118 approved these changes

2025-03-02 15:36 UTC, merged