added LineTV and tver
v2fly/domain-list-community pull request #463
Opened 2021-03-13 07:58 UTC by phlinhng

2021-03-13 08:20 UTC, IceCodeNew commented on data/tver
> +edge.api.brightcove.com
这个域名是如何得到的呢？

2021-03-13 08:21 UTC, IceCodeNew approved these changes

2021-03-13 08:21 UTC, IceCodeNew requested changes
请按字典序排序

2021-03-13 13:02 UTC, KevinZonda requested changes

2021-03-13 13:02 UTC, KevinZonda commented on data/tver
> +edge.api.brightcove.com
我认为Brightcove应该不是tver的？是另一个企业吧？

2021-03-13 21:23 UTC, phlinhng commented on data/tver
> +edge.api.brightcove.com
從 https://github.com/DivineEngine/Profiles/tree/ma%D1%95ter 裡面參考的

2021-03-13 21:25 UTC, phlinhng commented on data/tver
> +edge.api.brightcove.com
兩者似乎有合作關係？(https://ja.wikipedia.org/wiki/TVer)

2021-03-13 21:47 UTC, Loyalsoldier commented on data/tver
> +edge.api.brightcove.com
Brightcove 应该是 tver 的视频 CDN 服务提供商。

2021-03-13 22:11 UTC, KevinZonda commented on data/tver
> +edge.api.brightcove.com
是的，所以我觉得应该拆开

2021-03-14 03:07 UTC, Loyalsoldier commented
Thanks for your work. Closed due to https://github.com/v2fly/domain-list-community/pull/464

2021-03-14 03:07 UTC, closed without merging