Add vagrant
v2fly/domain-list-community pull request #590
Opened 2021-07-24 16:59 UTC by nyameteor

2021-07-24 18:21 UTC, IceCodeNew commented on data/vagrant
> +vagrantcloud.com
请按照字典序排列

2021-07-24 18:22 UTC, IceCodeNew requested changes
.

2021-07-24 19:07 UTC, Loyalsoldier commented
`vagrant` belongs to `hashicorp`, please update it in `hashicorp` instead.

2021-07-25 01:46 UTC, nyameteor commented on data/vagrant
> +vagrantcloud.com
好的，不好意思

2021-07-25 01:47 UTC, nyameteor commented
> `vagrant` belongs to `hashicorp`, please update it in `hashicorp` instead.

Oh.. I didn't see `vagrantup.com` in `hashicorp`, my apologies.

I saw `vagrantcloud.com` domain from vagrant log, but when I try `curl --head -L https://vagrantcloud.com`, it just redirects to https://app.vagrantup.com/, does this domain need to be added?

2021-07-25 02:03 UTC, Loyalsoldier commented
> > `vagrant` belongs to `hashicorp`, please update it in `hashicorp` instead.
> 
> Oh.. I didn't see `vagrantup.com` in `hashicorp`, my apologies.
> 
> I saw `vagrantcloud.com` domain from vagrant log, but when I try `curl --head -L https://vagrantcloud.com`, it just redirects to https://app.vagrantup.com/, does this domain need to be added?

Please add it.

2021-07-25 02:24 UTC, nyameteor commented
> > > `vagrant` belongs to `hashicorp`, please update it in `hashicorp` instead.
> > 
> > 
> > Oh.. I didn't see `vagrantup.com` in `hashicorp`, my apologies.
> > I saw `vagrantcloud.com` domain from vagrant log, but when I try `curl --head -L https://vagrantcloud.com`, it just redirects to https://app.vagrantup.com/, does this domain need to be added?
> 
> Please add it.

OK, I have added it to `hashicorp`, thanks.

2021-07-25 02:46 UTC, Loyalsoldier approved these changes

2021-07-25 02:46 UTC, merged