增加category-analytics
v2fly/domain-list-community pull request #611
Opened 2021-09-05 03:33 UTC by degfw

2021-09-05 05:50 UTC, IceCodeNew commented
If these domains are sorted out by others or referring to internet sources, please label them out.

2021-09-11 15:47 UTC, degfw commented
@IceCodeNew I'm sorry for so long to reply to you.

For these domains, `in.appcenter.ms` and `app-measurement.com` are found from my device, and others were collecting from GitHub. 

However, I couldn't re-find them all at once, so I can't referring their sources all here.

2021-09-11 16:04 UTC, IceCodeNew commented
> @IceCodeNew I'm sorry for so long to reply to you.
> 
> For these domains, `in.appcenter.ms` and `app-measurement.com` are found from my device, and others were collecting from GitHub.
> 
> However, I couldn't re-find them all at once, so I can't referring their sources all here.

Then you should only submit domains that you are sure they are utilizing ONLY for tracking.

2021-09-12 03:01 UTC, IceCodeNew commented on data/category-analytics
> +include:category-ads
should not include `ads` as they are completely different use cases.

2021-09-12 03:03 UTC, IceCodeNew commented on data/category-analytics
> +c.s-microsoft.com
If providing the referring sources turns to be difficult and painful, you could just concatenate all the domain lists that you have accessed during doing this PR, then give me the all-in-one list for me to do the review.

2021-09-12 03:04 UTC, IceCodeNew requested changes
If providing the referring sources turns to be difficult and painful, you could just concatenate all the domain lists that you have accessed during doing this PR, then give me the all-in-one list for me to do the review.

2021-09-12 03:23 UTC, degfw commented
The only domains I can find from my device are the three left, and they are used within Wechat, Clash, and Google's app.

2021-09-12 06:24 UTC, IceCodeNew commented
> The only domains I can find from my device are the three left, and they are used within Wechat, Clash, and Google's app.

I see. For approving these changes, may I ask how do you determine that these domains are for analytics purposes?

2021-09-13 02:02 UTC, KevinZonda requested changes

2021-09-13 02:02 UTC, KevinZonda commented on data/category-analytics
> +in.appcenter.ms
Would you mind providing this domain's purpose? I found it should be Microsoft App Center SDK. So it should not be kindly analysis tracker?

2021-09-13 02:02 UTC, KevinZonda commented
app-measurement.com is for firebase. [refer](app-measurement.com)  
analytics.map.qq.com is for Tencent Map /cc @IceCodeNew

2021-09-13 02:41 UTC, Loyalsoldier commented
Due to the lack of manpower, I personally recommend not collecting or adding "advertising" or "analytics" domains to the project. Instead we'd better use mature third-party projects that are compatible with MIT license.

Or let users generate their own geosite files after we refactor the project. I'd like to do it when I'm free lately.

2021-09-13 13:33 UTC, IceCodeNew commented
> Due to the lack of manpower, I personally recommend not collecting or adding "advertising" or "analytics" domains to the project. Instead we'd better use mature third-party projects that are compatible with MIT license.
> 
> Or let users generate their own geosite files after we refactor the project. I'd like to do it when I'm free lately.

I totally agree with that.

2021-09-13 22:42 UTC, KevinZonda commented
> Due to the lack of manpower, I personally recommend not collecting or adding "advertising" or "analytics" domains to the project. Instead we'd better use mature third-party projects that are compatible with MIT license.
> 
> Or let users generate their own geosite files after we refactor the project. I'd like to do it when I'm free lately.

It could be a better choice, totally agree with this.

So, should we close this issue? /cc @IceCodeNew @Loyalsoldier

2021-09-15 06:01 UTC, closed without merging