add pandanet
v2fly/domain-list-community pull request #679
Opened 2021-10-28 11:15 UTC by Jennal

pandanet is a global go game server, real slow in China

2021-11-10 08:08 UTC, Jennal commented on data/pandanet
> +igs.joyjoy.net
igs.joyjoy.net is the exact domain which has been used. then I would remove joyjoy.net

2021-11-10 11:04 UTC, IceCodeNew requested changes

2021-11-10 11:04 UTC, IceCodeNew commented on data/pandanet
> +igs.joyjoy.net
what's the point of marking as resolved if you just click that button while you haven't resolved the problem at all?

2021-11-18 02:14 UTC, Jennal commented
sorry..I don't know how to change the content of pull request. Click resolved is a mistake, I am so sorry for that.

2021-11-18 02:50 UTC, IceCodeNew approved these changes

2021-11-18 02:52 UTC, merged

2021-11-18 02:52 UTC, IceCodeNew commented
> sorry..I don't know how to change the content of pull request. Click resolved is a mistake, I am so sorry for that.

Never mind. Thanks for your contribution.