Create crunchyroll and funimation
v2fly/domain-list-community pull request #692
Opened 2021-11-13 15:27 UTC by Shelling0

Two mainstream anime steaming sites.

2021-11-14 00:23 UTC, IceCodeNew commented
Can you put these domains into some categories?

2021-11-14 08:03 UTC, Shelling0 commented
> Can you put these domains into some categories?

Crunchyroll and Funimation have been lumped together into **anime**, and more streaming sites have been added. 

Note that gogoanime, another anime site, has been added by someone else previously, and still remains a separate file. You may want to put gogoanime into **anime** as well.

2021-11-14 09:32 UTC, IceCodeNew commented
> > Can you put these domains into some categories?
> 
> Crunchyroll and Funimation have been lumped together into **anime**, and more streaming sites have been added.
> 
> Note that gogoanime, another anime site, has been added by someone else previously, and still remains a separate file. You may want to put gogoanime into **anime** as well.


Yes, I definitely want `gogoanime` to be put into the `anime` category.
Could you please accomplish that in this PR?

2021-11-14 09:33 UTC, IceCodeNew requested changes

2021-11-14 09:33 UTC, IceCodeNew commented on data/anime
> +#animedao
```suggestion
# animedao
```

2021-11-14 09:33 UTC, IceCodeNew commented on data/anime
> +9anime.id
Please sort these domains.

2021-11-14 12:24 UTC, Shelling0 commented
> > > Can you put these domains into some categories?
> > 
> > 
> > Crunchyroll and Funimation have been lumped together into **anime**, and more streaming sites have been added.
> > Note that gogoanime, another anime site, has been added by someone else previously, and still remains a separate file. You may want to put gogoanime into **anime** as well.
> 
> Yes, I definitely want `gogoanime` to be put into the `anime` category. Could you please accomplish that in this PR?

Sure.

2021-11-15 04:55 UTC, IceCodeNew approved these changes

2021-11-15 04:57 UTC, IceCodeNew reviewed
I am ok with these changes.
Only concerned about the deletion of the gogoanime file as this move could impact our users.

2021-11-28 03:25 UTC, IceCodeNew commented
Seems this PR is not getting care for about two weeks. I will merge this PR.
Anyway, we can do another PR to fix the problem should this PR cause.

2021-11-28 03:26 UTC, merged

2021-11-28 03:26 UTC, IceCodeNew commented
Thanks for your contribution!