Create manhuagui
v2fly/domain-list-community pull request #723
Opened 2021-12-18 07:18 UTC by jwstaceyOvO

2021-12-18 14:10 UTC, IceCodeNew commented on data/cygames
> +prd-storage-game-umamusume.akamaized.net
Please make another PR for this change.

2021-12-18 14:10 UTC, IceCodeNew requested changes
.

2021-12-18 14:14 UTC, IceCodeNew requested changes

2021-12-18 14:14 UTC, IceCodeNew commented on data/manhuagui
> +hamreus.com
![image](https://user-images.githubusercontent.com/32576256/146644062-78dc913d-4e68-416a-aac6-2f3013af4aef.png)

what the heck is this.

2021-12-18 14:29 UTC, jwstaceyOvO commented
I really don't know this, I caught 2 domains:i.hamreus.com and
cf.hamreus.com when downloading, so I write them as hamreus.com. If you
mind it, you can just change it as you like.

IceCodeNew ***@***.***> 于2021年12月18日周六 22:14写道：

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In data/manhuagui
> <https://github.com/v2fly/domain-list-community/pull/723#discussion_r771829546>
> :
>
> > @@ -0,0 +1,2 @@
> +manhuagui.com
> +hamreus.com
>
> [image: image]
> <https://user-images.githubusercontent.com/32576256/146644062-78dc913d-4e68-416a-aac6-2f3013af4aef.png>
>
> what the heck is this.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/v2fly/domain-list-community/pull/723#pullrequestreview-835777075>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJIUKGKZ74AVJHUYRVWJQHLURSJMLANCNFSM5KKK3CFA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2021-12-18 14:50 UTC, IceCodeNew approved these changes

2021-12-18 14:51 UTC, merged

2026-08-05 03:24 UTC, ayanamist commented
很奇怪 hamreus.com 的问题没人反馈
@IceCodeNew 这个域名看起来是个伪装（你截图的情况），从这个PR至今，一直在用这个域名做图床，而且带有IP校验
<img width="977" height="378" alt="image" src="https://github.com/user-attachments/assets/8538cdc8-746a-4310-a32d-29c82a8ff528" />
我是否可以提个PR加进来？