Update category-games
v2fly/domain-list-community pull request #759
Opened 2022-01-30 13:09 UTC by StoneMoe

Mihoyo is a game company

2022-02-05 14:46 UTC, rootmelo92118 commented
You need to consider alphabet sort, I think.

2022-02-06 12:54 UTC, KevinZonda requested changes
alphabet sort pls :)

2022-02-07 06:03 UTC, IceCodeNew approved these changes

2022-02-07 06:03 UTC, merged

2022-02-07 06:03 UTC, IceCodeNew commented
Thanks for your contribution!